(()=>{
const U=window.U,$=U.$,S=U.state;
const style=document.createElement('style');style.textContent=`
.audit-head{display:flex;justify-content:space-between;align-items:flex-end;gap:14px;margin-bottom:18px}.audit-head h1{margin:0 0 5px;font-size:30px;letter-spacing:-.7px}.audit-head p{margin:0;color:var(--muted);max-width:760px}.audit-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}.audit-stat{position:relative;overflow:hidden;background:var(--card);border:1px solid var(--line);border-radius:15px;padding:16px 17px}.audit-stat:before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--orange)}.audit-stat:nth-child(even):before{background:var(--blue)}.audit-stat span{display:block;font-size:10px;font-weight:800;color:var(--muted)}.audit-stat strong{display:block;margin-top:6px;font-size:24px;color:var(--text)}.audit-panel{background:var(--card);border:1px solid var(--line);border-top:3px solid var(--orange);border-radius:17px;overflow-x:auto;overflow-y:hidden}.audit-filters{display:grid;grid-template-columns:minmax(220px,1.5fr) repeat(3,minmax(150px,.7fr)) auto;gap:9px;padding:14px;border-bottom:1px solid var(--line);min-width:920px}.audit-filters input,.audit-filters select{width:100%;min-width:0;border:1px solid var(--line);background:var(--card);color:var(--text);border-radius:10px;padding:10px 11px}.audit-list{display:grid;min-width:920px}.audit-row{display:grid;grid-template-columns:minmax(105px,.7fr) minmax(145px,.95fr) minmax(130px,.8fr) minmax(220px,1.65fr) minmax(78px,.4fr);gap:12px;align-items:center;padding:13px 15px;border-bottom:1px solid var(--line)}.audit-row:last-child{border-bottom:0}.audit-time strong{display:block;font-size:11px}.audit-time small,.audit-actor small,.audit-change small{display:block;color:var(--muted);font-size:9px;margin-top:3px}.audit-actor strong,.audit-change strong{font-size:11px}.audit-action{display:inline-flex;align-items:center;max-width:100%;width:max-content;border-radius:999px;padding:5px 8px;background:var(--orange-soft);color:var(--orange);font-size:9px;font-weight:850}.audit-entity{color:var(--muted);font-size:9px;margin-top:4px}.audit-empty{padding:32px;text-align:center;color:var(--muted)}.audit-meta{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap;overflow-wrap:anywhere;background:var(--surface-soft);border:1px solid var(--line);padding:12px;border-radius:10px;font-size:11px;color:var(--text)}
html[data-theme="dark"] .audit-panel,html[data-theme="dark"] .audit-stat,html[data-theme="dark"] .audit-filters input,html[data-theme="dark"] .audit-filters select{background:var(--card)!important;border-color:var(--line)!important}
@media(max-width:1050px){.audit-filters{grid-template-columns:1fr 1fr}.audit-filters .audit-search{grid-column:1/-1}.audit-row{grid-template-columns:120px 1fr 1fr}.audit-change{grid-column:2/-1}.audit-row>button{grid-column:3;justify-self:end}}@media(max-width:650px){.audit-panel{overflow-x:hidden}.audit-filters,.audit-list{min-width:0}.audit-filters{grid-template-columns:1fr}.audit-filters .audit-search{grid-column:auto}.audit-row{grid-template-columns:1fr}.audit-change,.audit-row>button{grid-column:auto}.audit-row>button{justify-self:start}}
`;document.head.appendChild(style);
const labels={
 'user.create':'Usuario creado','user.update':'Usuario actualizado','user.password_reset':'Contraseña restablecida','enrollment.update':'Matrícula actualizada','course.create':'Curso creado','course.update':'Curso editado','course.archive':'Curso archivado','course.delete':'Curso eliminado','subject.create':'Materia creada','assignment.create':'Clase asignada','teacher.assignment_add':'Profesor agregó clase','year.create':'Año escolar creado','year.activate':'Año escolar activado','promotion.prepare':'Próximo año preparado','promotion.apply':'Estudiantes promovidos','evaluation.create':'Evaluación creada','evaluation.update':'Evaluación editada','grades.update':'Notas actualizadas','attendance.update':'Asistencia registrada','planning.create':'Planificación creada','planning.update':'Planificación editada','planning.delete':'Planificación eliminada','announcement.create':'Comunicado publicado','announcement.update':'Comunicado editado','announcement.archive':'Comunicado archivado'};
const roleLabel={admin:'Administrador',teacher:'Profesor',student:'Estudiante'};
const fmtTime=v=>{const d=new Date(v);return {date:new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d),time:new Intl.DateTimeFormat('es-CL',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(d)}};
const actionLabel=a=>labels[a]||String(a||'Cambio').replaceAll('_',' ');
U.renderAdminAudit=async()=>{
  const data=await U.api('/api/admin/audit-log?limit=300');S.audit=data;
  U.setPage('Registro de cambios','Auditoría y trazabilidad','<button id="auditRefresh" class="btn secondary">↻ Actualizar</button>');
  document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page==='admin-audit'));
  $('#content').innerHTML=`
    <div class="audit-head"><div><span class="eyebrow">Trazabilidad</span><h1>Registro de cambios</h1><p>Revisa quién modificó información académica o administrativa, qué acción realizó y cuándo ocurrió.</p></div></div>
    <div class="audit-stats"><div class="audit-stat"><span>Cambios registrados</span><strong>${data.summary.total}</strong></div><div class="audit-stat"><span>Hoy</span><strong>${data.summary.today}</strong></div><div class="audit-stat"><span>Últimos 7 días</span><strong>${data.summary.last7}</strong></div><div class="audit-stat"><span>Usuarios con actividad</span><strong>${data.summary.actors}</strong></div></div>
    <section class="audit-panel"><div class="audit-filters"><input id="auditQ" class="audit-search" placeholder="Buscar por usuario, descripción o ID"><select id="auditAction"><option value="">Todas las acciones</option>${data.actions.map(x=>`<option value="${U.esc(x.action)}">${U.esc(actionLabel(x.action))} (${x.total})</option>`).join('')}</select><select id="auditEntity"><option value="">Todos los tipos</option>${data.entities.map(x=>`<option value="${U.esc(x.entity_type)}">${U.esc(x.entity_type)} (${x.total})</option>`).join('')}</select><select id="auditActor"><option value="">Todos los usuarios</option>${data.actors.map(x=>`<option value="${x.id}">${U.esc(x.full_name)} · ${U.esc(roleLabel[x.role]||x.role)}</option>`).join('')}</select><button id="auditClear" class="btn ghost">Limpiar</button></div><div id="auditRows" class="audit-list"></div></section>`;
  const render=()=>{
    const q=$('#auditQ').value.trim().toLowerCase(),act=$('#auditAction').value,ent=$('#auditEntity').value,actor=$('#auditActor').value;
    const list=data.logs.filter(x=>(!q||`${x.actorName} ${x.description} ${x.entityId||''}`.toLowerCase().includes(q))&&(!act||x.action===act)&&(!ent||x.entityType===ent)&&(!actor||String(x.actorId)===actor));
    $('#auditRows').innerHTML=list.length?list.map(x=>{const t=fmtTime(x.createdAt),hasMeta=x.metadata&&Object.keys(x.metadata).length;return `<div class="audit-row"><div class="audit-time"><strong>${t.date}</strong><small>${t.time}</small></div><div class="audit-actor"><strong>${U.esc(x.actorName)}</strong><small>${U.esc(roleLabel[x.actorRole]||x.actorRole||'Sistema')}</small></div><div><span class="audit-action">${U.esc(actionLabel(x.action))}</span><div class="audit-entity">${U.esc(x.entityType)}${x.entityId?` · #${U.esc(x.entityId)}`:''}</div></div><div class="audit-change"><strong>${U.esc(x.description)}</strong><small>${U.esc(x.action)}</small></div>${hasMeta?`<button class="btn small ghost" data-audit-meta="${x.id}">Detalles</button>`:'<span></span>'}</div>`}).join(''):'<div class="audit-empty">No hay cambios que coincidan con los filtros.</div>';
  };
  ['auditQ','auditAction','auditEntity','auditActor'].forEach(id=>$('#'+id).addEventListener(id==='auditQ'?'input':'change',render));
  $('#auditClear').onclick=()=>{$('#auditQ').value='';$('#auditAction').value='';$('#auditEntity').value='';$('#auditActor').value='';render()};
  $('#auditRefresh').onclick=()=>U.renderAdminAudit();
  $('#auditRows').onclick=e=>{const b=e.target.closest('[data-audit-meta]');if(!b)return;const x=data.logs.find(v=>String(v.id)===b.dataset.auditMeta);if(!x)return;U.openModal('Detalles del cambio',`<p><strong>${U.esc(x.description)}</strong></p><div class="audit-meta">${U.esc(JSON.stringify(x.metadata,null,2))}</div>`)};
  render();
};
function ensureNav(){const nav=$('#nav');if(!nav||S.user?.role!=='admin'||S.adminPreview||nav.querySelector('[data-page="admin-audit"]'))return;const b=document.createElement('button');b.type='button';b.className='nav-btn';b.dataset.page='admin-audit';b.innerHTML='<span class="nav-icon">≣</span><span>Registro de cambios</span>';const hist=nav.querySelector('[data-page="admin-history"]');nav.insertBefore(b,hist||null)}
const baseShell=U.renderShell;U.renderShell=()=>{baseShell();ensureNav()};
const baseNavigate=U.navigate;U.navigate=async page=>{if(page!=='admin-audit')return baseNavigate(page);S.page=page;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#content').innerHTML='<div class="card empty">Cargando registro de cambios…</div>';try{return await U.renderAdminAudit()}catch(e){$('#content').innerHTML=`<div class="card"><h2>No se pudo cargar el registro</h2><p class="form-error">${U.esc(e.message)}</p><button id="retryAudit" class="btn ghost">Reintentar</button></div>`;$('#retryAudit').onclick=()=>U.navigate('admin-audit')}};
setTimeout(ensureNav,0);const nav=$('#nav');if(nav)new MutationObserver(()=>setTimeout(ensureNav,0)).observe(nav,{childList:true});
})();