(()=>{
const U=window.U,$=U.$,S=U.state;
const today=()=>{const d=new Date(),z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,10)};
const shiftDate=(v,n)=>{const d=new Date(`${v}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
const longDate=v=>new Intl.DateTimeFormat('es-CL',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${v}T00:00:00Z`));

const style=document.createElement('style');style.textContent=`
.att-tabs{display:flex;gap:6px;padding:5px;background:#edf3f7;border-radius:13px;width:max-content}.att-tab{border:0;background:transparent;color:#607080;border-radius:9px;padding:9px 14px;font-weight:800;font-size:12px}.att-tab.active{background:#fff;color:var(--blue);box-shadow:0 3px 12px rgba(16,38,59,.08)}
.att-hero{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin-bottom:20px}.att-hero h1{margin:0 0 6px;font-size:30px;letter-spacing:-.8px}.att-hero p{margin:0;color:var(--muted)}
.att-date-tools{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.att-date-tools input{border:1px solid var(--line);background:#fff;border-radius:10px;padding:9px 11px;font-weight:750;color:var(--blue)}
.att-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-bottom:18px}.att-summary-card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:17px 18px;box-shadow:var(--shadow-soft)}.att-summary-card small{display:block;color:var(--muted);font-weight:700}.att-summary-card strong{display:block;margin-top:5px;font-size:27px;color:var(--blue)}.att-summary-card.present strong{color:#16865c}.att-summary-card.absent strong{color:#c84b3a}.att-summary-card.unmarked strong{color:#9b6b13}
.att-days{display:flex;gap:8px;overflow:auto;padding:2px 1px 12px;margin-bottom:6px}.att-day{flex:0 0 auto;border:1px solid var(--line);background:#fff;border-radius:12px;padding:9px 12px;text-align:left;min-width:128px;color:var(--text)}.att-day.active{border-color:#9bb8cc;background:#edf5f9;box-shadow:0 5px 16px rgba(7,55,90,.08)}.att-day strong{display:block;font-size:12px}.att-day small{display:block;color:var(--muted);margin-top:3px;font-size:10px}
.att-panel{background:#fff;border:1px solid var(--line);border-radius:18px;box-shadow:var(--shadow-soft);overflow:hidden}.att-panel-head{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:14px 16px;border-bottom:1px solid var(--line);flex-wrap:wrap}.att-panel-head .search{max-width:520px}.att-auto{font-size:11px;color:var(--muted);font-weight:700}
.att-row{display:grid;grid-template-columns:minmax(230px,1fr) 280px;align-items:center;gap:16px;padding:13px 16px;border-bottom:1px solid #edf1f4}.att-row:last-child{border-bottom:0}.att-student{display:flex;gap:10px;align-items:center;min-width:0}.att-student-copy{min-width:0}.att-student strong{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.att-student small{display:block;color:var(--muted);margin-top:2px}.att-choices{display:grid;grid-template-columns:1fr 1fr;gap:8px}.att-choice{border:1px solid #dce4ea;background:#fafcfd;border-radius:10px;padding:9px 10px;font-weight:800;font-size:12px;color:#687582;transition:.15s}.att-choice:hover{transform:translateY(-1px)}.att-choice.present.active{background:#e9f7f0;border-color:#b8e3cf;color:#167152}.att-choice.absent.active{background:#fff0ec;border-color:#f2c4b7;color:#b84427}.att-choice:disabled{opacity:.82;cursor:default;transform:none}.att-none{padding:36px;text-align:center;color:var(--muted)}
.att-preview-banner{display:flex;justify-content:space-between;align-items:center;gap:12px;background:#fff7f2;border:1px solid #f4d5c8;border-radius:14px;padding:12px 14px;margin-bottom:16px;color:#9b4b2f;font-size:12px;font-weight:700}
@media(max-width:780px){.att-hero{align-items:flex-start;flex-direction:column}.att-summary{grid-template-columns:1fr}.att-row{grid-template-columns:1fr}.att-choices{max-width:none}.att-date-tools{width:100%}.att-date-tools input{flex:1}.att-tabs{width:100%}.att-tab{flex:1}}
`;document.head.appendChild(style);

/* Vista real del profesor: mantiene el libro de notas y agrega Asistencia. */
const baseTeacherClass=U.renderTeacherClass;
if(typeof baseTeacherClass==='function')U.renderTeacherClass=async id=>{
  await baseTeacherClass(id);
  const actions=$('#topActions');
  if(actions&&!$('#openAttendance'))actions.insertAdjacentHTML('beforeend','<button id="openAttendance" type="button" class="btn secondary">✓ Asistencia</button>');
  const b=$('#openAttendance');if(b)b.onclick=()=>renderAttendance(id,S.attendanceDate||today());
};

async function renderAttendance(id,date=today()){
  S.attendanceDate=date;S.attendanceAssignmentId=id;
  const [d,history]=await Promise.all([U.api(`/api/teacher/assignments/${id}/attendance?date=${encodeURIComponent(date)}`),U.api(`/api/teacher/assignments/${id}/attendance/dates`)]);
  U.setPage(`${d.assignment.courseName} · ${d.assignment.subjectName}`,`Asistencia · ${d.assignment.year}`,'<button id="attendanceBack" class="btn ghost">← Libro de notas</button>');
  const days=[{date:today(),present:0,absent:0},...(history.days||[])].filter((x,i,a)=>a.findIndex(y=>y.date===x.date)===i).slice(0,16);
  $('#content').innerHTML=`
    <div class="att-hero"><div><div class="att-tabs"><button class="att-tab" id="attNotesTab">Notas</button><button class="att-tab active">Asistencia</button></div><h1 style="margin-top:16px">Control de asistencia</h1><p>Registra la asistencia diaria. Cada cambio se guarda automáticamente.</p></div><div class="att-date-tools"><button class="btn ghost" id="attPrev">←</button><input id="attendanceDate" type="date" value="${date}"><button class="btn ghost" id="attNext">→</button><button class="btn secondary" id="attToday">Hoy</button></div></div>
    <div class="att-summary"><div class="att-summary-card present"><small>Presentes</small><strong>${d.summary.present}</strong></div><div class="att-summary-card absent"><small>Ausentes</small><strong>${d.summary.absent}</strong></div><div class="att-summary-card unmarked"><small>Sin registrar</small><strong>${d.summary.unmarked}</strong></div></div>
    <div class="att-days">${days.map(x=>`<button class="att-day ${x.date===date?'active':''}" data-att-day="${x.date}"><strong>${x.date===today()?'Hoy':U.fmtDate(x.date)}</strong><small>${x.present+x.absent?`${x.present} presentes · ${x.absent} ausentes`:'Sin registros'}</small></button>`).join('')}</div>
    <div class="att-panel"><div class="att-panel-head"><input id="attendanceSearch" class="search" placeholder="Buscar estudiante por nombre o RUT"><div class="group"><span class="att-auto">Guardado automático</span><button id="markAllPresent" class="btn secondary">Todos presentes</button></div></div><div id="attendanceRows">${attendanceRows(d.students,false)}</div></div>`;
  $('#attendanceBack').onclick=()=>U.renderTeacherClass(id);$('#attNotesTab').onclick=()=>U.renderTeacherClass(id);
  $('#attPrev').onclick=()=>renderAttendance(id,shiftDate(date,-1));$('#attNext').onclick=()=>renderAttendance(id,shiftDate(date,1));$('#attToday').onclick=()=>renderAttendance(id,today());
  $('#attendanceDate').onchange=e=>{if(e.target.value)renderAttendance(id,e.target.value)};
  $('#attendanceSearch').oninput=e=>{const q=String(e.target.value||'').toLowerCase().trim();document.querySelectorAll('[data-att-row]').forEach(r=>r.hidden=q&&!r.dataset.search.includes(q))};
  $('#content').onclick=async e=>{
    const day=e.target.closest('[data-att-day]');if(day)return renderAttendance(id,day.dataset.attDay);
    const choice=e.target.closest('[data-att-status]');if(!choice)return;
    choice.disabled=true;
    try{await U.api(`/api/teacher/assignments/${id}/attendance`,{method:'POST',body:{date,records:[{studentId:Number(choice.dataset.student),status:choice.dataset.attStatus}]}});await renderAttendance(id,date)}catch(err){U.toast(err.message);choice.disabled=false}
  };
  $('#markAllPresent').onclick=async()=>{const btn=$('#markAllPresent');btn.disabled=true;btn.textContent='Guardando…';try{await U.api(`/api/teacher/assignments/${id}/attendance`,{method:'POST',body:{date,records:d.students.map(s=>({studentId:s.id,status:'present'}))}});await renderAttendance(id,date);U.toast('Todos marcados como presentes')}catch(err){U.toast(err.message);btn.disabled=false;btn.textContent='Todos presentes'}};
}
function attendanceRows(students,readonly){
  if(!students.length)return '<div class="att-none">No hay estudiantes matriculados en este curso.</div>';
  return students.map(s=>`<div class="att-row" data-att-row data-search="${U.esc((s.fullName+' '+U.fmtRut(s.rut)).toLowerCase())}"><div class="att-student"><div class="avatar">${U.esc(U.initials(s.fullName))}</div><div class="att-student-copy"><strong>${U.esc(s.fullName)}</strong><small>${U.esc(U.fmtRut(s.rut))}</small></div></div><div class="att-choices"><button ${readonly?'disabled':''} class="att-choice present ${s.status==='present'?'active':''}" data-student="${s.id}" data-att-status="present">✓ Presente</button><button ${readonly?'disabled':''} class="att-choice absent ${s.status==='absent'?'active':''}" data-student="${s.id}" data-att-status="absent">× Ausente</button></div></div>`).join('');
}

/* La vista rápida del administrador replica el aspecto actual del profesor. */
function sampleTeacher(){return {previewUser:{id:0,fullName:'Carlos Soto',rut:'15234567-8'},activeYear:{year:new Date().getFullYear()},assignments:[{id:'sample-math',courseName:'3° Medio B',subjectName:'Matemáticas',studentCount:32,evaluationCount:4},{id:'sample-physics',courseName:'3° Medio B',subjectName:'Física',studentCount:32,evaluationCount:3},{id:'sample-math2',courseName:'2° Medio A',subjectName:'Matemáticas',studentCount:29,evaluationCount:4}]}}
function sampleClass(id){const a=sampleTeacher().assignments.find(x=>x.id===id)||sampleTeacher().assignments[0],students=['Ana Pérez','Diego Soto','Martín Silva','Camila Fuentes','Joaquín Rojas'].map((fullName,i)=>({id:i+1,rut:`2000000${i+1}-${i}`,fullName}));const evaluations=[{id:101,name:'Prueba 1',semester:2,weight:25,status:'completed'},{id:102,name:'Trabajo',semester:2,weight:20,status:'completed'},{id:103,name:'Prueba 2',semester:2,weight:30,status:'completed'},{id:104,name:'Proyecto',semester:2,weight:25,status:'pending'}],vals=[[6.2,5.8,6.0],[4.8,5.4,5.1],[5.9,6.4,5.7],[6.7,6.5,6.3],[5.0,5.6,4.9]],grades=[];students.forEach((s,i)=>evaluations.slice(0,3).forEach((e,j)=>grades.push({evaluationId:e.id,studentId:s.id,grade:vals[i][j]})));return {assignment:{id:a.id,courseName:a.courseName,subjectName:a.subjectName,year:new Date().getFullYear()},students,evaluations,grades}}
function sampleAttendance(id,date){const c=sampleClass(id),cycle=['present','present','absent','present',null];const students=c.students.map((s,i)=>({...s,status:cycle[(i+Number(date.slice(-2)))%cycle.length]}));return {assignment:c.assignment,date,students,summary:{present:students.filter(x=>x.status==='present').length,absent:students.filter(x=>x.status==='absent').length,unmarked:students.filter(x=>!x.status).length},days:[{date:today(),present:4,absent:1},{date:shiftDate(today(),-1),present:3,absent:2},{date:shiftDate(today(),-2),present:5,absent:0}]}}

async function mirrorPreviewHome(){
  const p=S.adminPreview;if(S.user?.role!=='admin'||p?.role!=='teacher')return;
  const c=$('#content'),title=$('#pageTitle');if(!c||title?.textContent!=='Panel del profesor')return;
  const key=`${p.sample?'sample':p.user?.id}`;if(c.dataset.teacherMirror===key||c.dataset.teacherMirror===`loading-${key}`)return;c.dataset.teacherMirror=`loading-${key}`;
  try{const d=p.sample?sampleTeacher():await U.api(`/api/admin/preview/teacher/${p.user.id}`);if(S.adminPreview!==p)return;c.dataset.teacherMirror=key;const studentTotal=d.assignments.reduce((n,a)=>n+Number(a.studentCount||0),0),evalTotal=d.assignments.reduce((n,a)=>n+Number(a.evaluationCount||0),0),courseTotal=new Set(d.assignments.map(a=>a.courseName)).size,subjectTotal=new Set(d.assignments.map(a=>a.subjectName)).size,first=String(d.previewUser.fullName||'Profesor').split(' ')[0];c.innerHTML=`<div class="att-preview-banner"><span>Vista rápida actualizada · mismo diseño del panel real del profesor</span><span>Solo lectura</span></div><section class="teacher-hero"><div class="teacher-hero-copy"><span class="teacher-kicker">Tu espacio docente</span><h1>Hola, ${U.esc(first)} 👋</h1><p>Organiza tus cursos, materias, evaluaciones, notas y asistencia desde un solo lugar.</p></div><div class="teacher-add-card" style="cursor:default"><span class="teacher-add-icon">+</span><span><strong>Agregar curso y materia</strong><small>Disponible en la cuenta real del profesor</small></span><span class="badge warn">Solo lectura</span></div></section><div class="teacher-stat-grid"><div class="teacher-stat-card"><span class="teacher-stat-icon">▤</span><div><small>Clases asignadas</small><strong>${d.assignments.length}</strong></div></div><div class="teacher-stat-card"><span class="teacher-stat-icon">◎</span><div><small>Cursos</small><strong>${courseTotal}</strong></div></div><div class="teacher-stat-card"><span class="teacher-stat-icon orange">▦</span><div><small>Materias</small><strong>${subjectTotal}</strong></div></div><div class="teacher-stat-card"><span class="teacher-stat-icon green">✓</span><div><small>Evaluaciones</small><strong>${evalTotal}</strong></div></div></div><div class="teacher-section-head"><div><span class="eyebrow">Organización</span><h2>Mis cursos y materias</h2><p>Selecciona una clase para revisar notas y asistencia.</p></div><span class="teacher-student-count">${studentTotal} estudiantes vinculados</span></div><div class="teacher-course-grid">${d.assignments.map((a,i)=>`<button type="button" class="teacher-course-card" data-att-preview-class="${a.id}"><span class="teacher-course-accent accent-${i%3}"></span><div class="teacher-course-top"><span class="teacher-course-pill">${U.esc(a.courseName)}</span><span class="teacher-course-open">Abrir →</span></div><h3>${U.esc(a.subjectName)}</h3><div class="teacher-course-meta"><span><b>${a.studentCount}</b> estudiantes</span><span><b>${a.evaluationCount}</b> evaluaciones</span></div></button>`).join('')||'<div class="teacher-empty-state"><h3>Sin clases asignadas</h3><p>La vista se actualizará cuando el profesor agregue cursos y materias.</p></div>'}</div>`;c.onclick=e=>{const b=e.target.closest('[data-att-preview-class]');if(b)renderPreviewClass(String(b.dataset.attPreviewClass),p.sample)}}catch(e){c.dataset.teacherMirror='';}
}
async function renderPreviewClass(id,isSample){
  const p=S.adminPreview;if(!p)return;const d=isSample?sampleClass(id):await U.api(`/api/admin/preview/teacher/${p.user.id}/assignments/${id}`);S.previewTeacherClass=d;U.setPage(`${d.assignment.courseName} · ${d.assignment.subjectName}`,'Vista rápida del profesor',$('#topActions')?.innerHTML||'');
  const sem=2,evs=d.evaluations.filter(e=>e.semester===sem),gm=new Map(d.grades.map(g=>[`${g.evaluationId}-${g.studentId}`,g.grade]));
  $('#content').innerHTML=`<div class="att-preview-banner"><span>Vista del profesor · solo lectura</span><button id="previewBackCourses" class="btn small ghost">← Mis cursos</button></div><div class="att-hero"><div><div class="att-tabs"><button class="att-tab active">Notas</button><button id="previewAttendanceTab" class="att-tab">Asistencia</button></div><h1 style="margin-top:16px">Libro de notas</h1><p>Así ve esta clase el profesor.</p></div></div><div class="panel"><div class="table-wrap" style="border:0"><table><thead><tr><th>Estudiante</th>${evs.map(e=>`<th>${U.esc(e.name)}<span class="weight">${e.weight}%</span></th>`).join('')}</tr></thead><tbody>${d.students.map(s=>`<tr><td><strong>${U.esc(s.fullName)}</strong><span class="weight">${U.esc(U.fmtRut(s.rut))}</span></td>${evs.map(e=>`<td class="grade">${gm.get(`${e.id}-${s.id}`)==null?'<span class="pending">Pendiente</span>':Number(gm.get(`${e.id}-${s.id}`)).toFixed(1)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`;
  $('#previewBackCourses').onclick=()=>{delete $('#content').dataset.teacherMirror;U.setPage('Panel del profesor',`Año escolar ${d.assignment.year}`,$('#topActions')?.innerHTML||'');mirrorPreviewHome()};$('#previewAttendanceTab').onclick=()=>renderPreviewAttendance(id,today(),isSample);
}
async function renderPreviewAttendance(id,date,isSample){
  const p=S.adminPreview;if(!p)return;const d=isSample?sampleAttendance(id,date):await U.api(`/api/admin/preview/teacher/${p.user.id}/assignments/${id}/attendance?date=${encodeURIComponent(date)}`),days=(d.days||[]);U.setPage(`${d.assignment.courseName} · ${d.assignment.subjectName}`,'Asistencia · vista rápida',$('#topActions')?.innerHTML||'');
  $('#content').innerHTML=`<div class="att-preview-banner"><span>Asistencia del profesor · solo lectura</span><button id="previewBackNotes" class="btn small ghost">← Libro de notas</button></div><div class="att-hero"><div><div class="att-tabs"><button id="previewNotesTab" class="att-tab">Notas</button><button class="att-tab active">Asistencia</button></div><h1 style="margin-top:16px">Control de asistencia</h1><p>${U.esc(longDate(date))}</p></div><div class="att-date-tools"><button id="prevPreviewDay" class="btn ghost">←</button><input id="previewAttDate" type="date" value="${date}"><button id="nextPreviewDay" class="btn ghost">→</button></div></div><div class="att-summary"><div class="att-summary-card present"><small>Presentes</small><strong>${d.summary.present}</strong></div><div class="att-summary-card absent"><small>Ausentes</small><strong>${d.summary.absent}</strong></div><div class="att-summary-card unmarked"><small>Sin registrar</small><strong>${d.summary.unmarked}</strong></div></div><div class="att-days">${days.slice(0,12).map(x=>`<button class="att-day ${x.date===date?'active':''}" data-preview-day="${x.date}"><strong>${x.date===today()?'Hoy':U.fmtDate(x.date)}</strong><small>${x.present} presentes · ${x.absent} ausentes</small></button>`).join('')}</div><div class="att-panel"><div class="att-panel-head"><span class="att-auto">Solo lectura</span></div>${attendanceRows(d.students,true)}</div>`;
  const back=()=>renderPreviewClass(id,isSample);$('#previewBackNotes').onclick=back;$('#previewNotesTab').onclick=back;$('#prevPreviewDay').onclick=()=>renderPreviewAttendance(id,shiftDate(date,-1),isSample);$('#nextPreviewDay').onclick=()=>renderPreviewAttendance(id,shiftDate(date,1),isSample);$('#previewAttDate').onchange=e=>{if(e.target.value)renderPreviewAttendance(id,e.target.value,isSample)};$('#content').onclick=e=>{const b=e.target.closest('[data-preview-day]');if(b)renderPreviewAttendance(id,b.dataset.previewDay,isSample)};
}

let mirrorTimer;const observer=new MutationObserver(()=>{clearTimeout(mirrorTimer);mirrorTimer=setTimeout(mirrorPreviewHome,60)});const content=$('#content');if(content)observer.observe(content,{childList:true,subtree:false});document.addEventListener('click',()=>setTimeout(mirrorPreviewHome,100));
})();
