(()=>{
const U=window.U,$=U.$,S=U.state;
const style=document.createElement('style');
style.textContent=`
.comm-head{display:flex;align-items:flex-end;justify-content:space-between;gap:16px;margin-bottom:18px}.comm-head h1{margin:0 0 5px;font-size:30px;letter-spacing:-.8px}.comm-head p{margin:0;color:var(--muted);max-width:720px}.comm-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-bottom:18px}.comm-stat{background:var(--card);border:1px solid var(--line);border-top:3px solid var(--orange);border-radius:15px;padding:16px;box-shadow:var(--shadow-soft)}.comm-stat span{display:block;color:var(--muted);font-size:11px;font-weight:750}.comm-stat strong{display:block;margin-top:6px;font-size:24px;color:var(--text)}
.comm-layout{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:16px;align-items:start}.comm-list{display:grid;gap:12px}.comm-card{position:relative;background:var(--card);border:1px solid var(--line);border-left:4px solid var(--blue);border-radius:17px;padding:18px 19px;box-shadow:var(--shadow-soft);overflow:hidden}.comm-card.important{border-left-color:var(--orange);background:linear-gradient(90deg,var(--orange-soft),var(--card) 18%)}.comm-card.archived{opacity:.68}.comm-card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.comm-card h2{font-size:17px;margin:0 0 5px}.comm-meta{display:flex;gap:7px;flex-wrap:wrap;align-items:center;color:var(--muted);font-size:10px}.comm-body{margin:13px 0 0;color:var(--text);font-size:13px;line-height:1.58;white-space:pre-wrap}.comm-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:14px}.comm-side{background:var(--card);border:1px solid var(--line);border-top:3px solid var(--orange);border-radius:17px;padding:17px;box-shadow:var(--shadow-soft)}.comm-side h3{margin:0 0 7px;font-size:16px}.comm-side p{color:var(--muted);font-size:11px;line-height:1.5}.comm-key{display:grid;gap:9px;margin-top:14px}.comm-key-row{display:flex;gap:9px;align-items:flex-start;padding:10px;border-radius:11px;background:var(--surface-soft)}.comm-dot{width:9px;height:9px;border-radius:999px;background:var(--blue);margin-top:3px;flex:0 0 auto}.comm-dot.orange{background:var(--orange)}.comm-key-row strong{display:block;font-size:11px}.comm-key-row small{display:block;color:var(--muted);font-size:10px;margin-top:2px}.comm-empty{background:var(--card);border:1px dashed var(--line);border-radius:17px;padding:36px 20px;text-align:center;color:var(--muted)}.comm-preview-banner{display:flex;justify-content:space-between;gap:10px;background:var(--orange-soft);border:1px solid rgba(235,82,31,.25);border-radius:13px;padding:10px 12px;margin-bottom:14px;color:var(--orange);font-size:11px;font-weight:800}.comm-form-note{background:var(--surface-soft);border:1px solid var(--line);border-radius:11px;padding:10px 11px;color:var(--muted);font-size:11px;line-height:1.45}
html[data-theme="dark"] .comm-card,html[data-theme="dark"] .comm-side,html[data-theme="dark"] .comm-stat{background:var(--card)!important;border-color:var(--line)!important;color:var(--text)!important}html[data-theme="dark"] .comm-card.important{background:linear-gradient(90deg,#2a1b17,var(--card) 18%)!important}html[data-theme="dark"] .comm-key-row{background:var(--surface-soft)!important}
@media(max-width:980px){.comm-layout{grid-template-columns:1fr}.comm-summary{grid-template-columns:1fr 1fr 1fr}}@media(max-width:650px){.comm-head{align-items:flex-start;flex-direction:column}.comm-summary{grid-template-columns:1fr}.comm-card-head{flex-direction:column}.comm-layout{display:block}.comm-side{margin-top:14px}}
`;
document.head.appendChild(style);

const audienceLabel=(a,c)=>a==='all'?'Todo el liceo':a==='students'?'Todos los estudiantes':a==='teachers'?'Todos los profesores':a==='course'?(c||'Curso específico'):'Destinatarios';
const fmtTime=v=>v?new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'—';
function card(a,admin=false){return `<article class="comm-card ${a.priority==='important'?'important':''} ${a.active===false?'archived':''}"><div class="comm-card-head"><div><div class="comm-meta">${a.priority==='important'?'<span class="badge warn">Importante</span>':''}<span class="badge blue">${U.esc(audienceLabel(a.audience,a.courseName))}</span>${a.active===false?'<span class="badge">Archivado</span>':''}</div><h2>${U.esc(a.title)}</h2><div class="comm-meta"><span>${U.esc(a.authorName||'Administración')}</span><span>·</span><span>${fmtTime(a.createdAt)}</span>${a.expiresOn?`<span>· visible hasta ${U.fmtDate(a.expiresOn)}</span>`:''}</div></div></div><p class="comm-body">${U.esc(a.body)}</p>${admin?`<div class="comm-actions"><button class="btn small secondary" data-comm-edit="${a.id}">Editar</button>${a.active!==false?`<button class="btn small ghost" data-comm-archive="${a.id}">Archivar</button>`:''}</div>`:''}</article>`}

async function renderFeed({preview=false,sample=false,role=null}={}){
  let d;if(preview){const p=S.adminPreview;if(sample)d=sampleFeed(p?.role||role);else d=await U.api(`/api/communications/preview/${p.role}/${p.user.id}`)}else d=await U.api('/api/communications/feed');
  const items=d.announcements||[],important=items.filter(x=>x.priority==='important').length;
  U.setPage('Comunicados',`Año escolar ${d.activeYear?.year||''}`,preview?`<span class="badge warn">${sample?'Vista de ejemplo · sin cuenta':'Vista previa · solo lectura'}</span><button id="exitPreviewV2" class="btn ghost">Volver a administración</button>`:'');
  document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',preview?b.hasAttribute('data-preview-communications'):b.dataset.page==='communications'));
  $('#content').innerHTML=`${preview?'<div class="comm-preview-banner"><span>Vista rápida de comunicados</span><span>Solo lectura</span></div>':''}<div class="comm-head"><div><span class="eyebrow">Información del liceo</span><h1>Comunicados</h1><p>Avisos importantes, información general y mensajes dirigidos a tu comunidad escolar.</p></div></div><div class="comm-summary"><div class="comm-stat"><span>Comunicados visibles</span><strong>${items.length}</strong></div><div class="comm-stat"><span>Importantes</span><strong>${important}</strong></div><div class="comm-stat"><span>Última actualización</span><strong style="font-size:16px">${items[0]?fmtTime(items[0].createdAt):'Sin avisos'}</strong></div></div><div class="comm-layout"><section class="comm-list">${items.length?items.map(x=>card(x,false)).join(''):'<div class="comm-empty"><strong>No hay comunicados por ahora.</strong><div style="margin-top:5px">Cuando administración publique uno, aparecerá aquí.</div></div>'}</section><aside class="comm-side"><h3>Cómo funciona</h3><p>Administración puede publicar avisos para todo el liceo, solo estudiantes, solo profesores o un curso específico.</p><div class="comm-key"><div class="comm-key-row"><span class="comm-dot orange"></span><div><strong>Importante</strong><small>Información prioritaria que conviene revisar primero.</small></div></div><div class="comm-key-row"><span class="comm-dot"></span><div><strong>Informativo</strong><small>Avisos generales de la comunidad escolar.</small></div></div></div></aside></div>`;
  const exit=$('#exitPreviewV2');if(exit)exit.onclick=()=>{S.adminPreview=null;U.renderShell();U.navigate('admin-home')};
}

async function renderAdmin(){
  const d=await U.api('/api/communications/admin');S.communicationsAdmin=d;const active=d.announcements.filter(x=>x.active),important=active.filter(x=>x.priority==='important').length;
  U.setPage('Comunicados',`Año escolar ${d.activeYear.year}`,'<button id="newCommunication" class="btn primary">+ Nuevo comunicado</button>');
  document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page==='admin-communications'));
  $('#content').innerHTML=`<div class="comm-head"><div><span class="eyebrow">Administración</span><h1>Comunicados</h1><p>Publica información para toda la comunidad o dirige avisos a grupos específicos.</p></div></div><div class="comm-summary"><div class="comm-stat"><span>Activos</span><strong>${active.length}</strong></div><div class="comm-stat"><span>Importantes</span><strong>${important}</strong></div><div class="comm-stat"><span>Archivados</span><strong>${d.announcements.length-active.length}</strong></div></div><div class="comm-layout"><section class="comm-list">${d.announcements.length?d.announcements.map(x=>card(x,true)).join(''):'<div class="comm-empty">Aún no has publicado comunicados.</div>'}</section><aside class="comm-side"><h3>Destinatarios</h3><p>Puedes publicar para todo el liceo o limitar un aviso a estudiantes, profesores o un curso.</p><div class="comm-key"><div class="comm-key-row"><span class="comm-dot orange"></span><div><strong>Usa “Importante” con moderación</strong><small>Así los avisos realmente urgentes destacan.</small></div></div><div class="comm-key-row"><span class="comm-dot"></span><div><strong>Fecha de vencimiento</strong><small>Opcional. Después de esa fecha deja de mostrarse automáticamente.</small></div></div></div></aside></div>`;
  $('#newCommunication').onclick=()=>openForm(d,null);
  $('#content').onclick=e=>{const ed=e.target.closest('[data-comm-edit]'),ar=e.target.closest('[data-comm-archive]');if(ed){const a=d.announcements.find(x=>x.id===Number(ed.dataset.commEdit));if(a)openForm(d,a)}if(ar)archive(Number(ar.dataset.commArchive))};
}
function openForm(d,item){
  const isEdit=!!item;U.openModal(isEdit?'Editar comunicado':'Nuevo comunicado',`<form id="communicationForm" class="stack"><div class="field"><label>Título</label><input name="title" maxlength="120" value="${U.esc(item?.title||'')}" required></div><div class="field"><label>Mensaje</label><textarea name="body" rows="7" maxlength="4000" required>${U.esc(item?.body||'')}</textarea></div><div class="form-grid"><div class="field"><label>Destinatarios</label><select name="audience" id="commAudience"><option value="all" ${item?.audience==='all'?'selected':''}>Todo el liceo</option><option value="students" ${item?.audience==='students'?'selected':''}>Todos los estudiantes</option><option value="teachers" ${item?.audience==='teachers'?'selected':''}>Todos los profesores</option><option value="course" ${item?.audience==='course'?'selected':''}>Curso específico</option></select></div><div class="field"><label>Prioridad</label><select name="priority"><option value="normal" ${item?.priority!=='important'?'selected':''}>Normal</option><option value="important" ${item?.priority==='important'?'selected':''}>Importante</option></select></div></div><div class="field" id="commCourseField"><label>Curso</label><select name="courseId">${d.courses.map(c=>`<option value="${c.id}" ${Number(item?.courseId)===Number(c.id)?'selected':''}>${U.esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Visible hasta <span class="muted">(opcional)</span></label><input type="date" name="expiresOn" value="${U.esc(item?.expiresOn||'')}"></div><div class="comm-form-note">Si no defines una fecha de vencimiento, el comunicado seguirá visible hasta que lo archives.</div><div class="form-actions"><button type="button" class="btn ghost" data-close>Cancelar</button><button class="btn primary">${isEdit?'Guardar cambios':'Publicar comunicado'}</button></div></form>`);
  const f=$('#communicationForm'),aud=$('#commAudience'),course=$('#commCourseField');const sync=()=>course.hidden=aud.value!=='course';sync();aud.onchange=sync;$('[data-close]').onclick=U.closeModal;
  f.onsubmit=async e=>{e.preventDefault();const x=new FormData(f),body={title:x.get('title'),body:x.get('body'),audience:x.get('audience'),priority:x.get('priority'),courseId:x.get('audience')==='course'?Number(x.get('courseId')):null,expiresOn:x.get('expiresOn')||null};try{await U.api(isEdit?`/api/communications/admin/${item.id}`:'/api/communications/admin',{method:isEdit?'PATCH':'POST',body});U.closeModal();U.toast(isEdit?'Comunicado actualizado':'Comunicado publicado');renderAdmin()}catch(err){U.toast(err.message)}};
}
async function archive(id){if(!confirm('¿Archivar este comunicado? Dejará de mostrarse a los usuarios.'))return;try{await U.api(`/api/communications/admin/${id}`,{method:'DELETE'});U.toast('Comunicado archivado');renderAdmin()}catch(e){U.toast(e.message)}}
function sampleFeed(role='student'){const y=S.admin?.activeYear?.year||new Date().getFullYear(),today=new Date().toISOString();return {activeYear:{year:y},announcements:[{id:-1,title:'Reunión general de apoderados',body:'Se informa a la comunidad que la próxima reunión general se realizará el jueves a las 18:00 horas.',audience:'all',priority:'important',active:true,createdAt:today,authorName:'Administración'},{id:-2,title:role==='teacher'?'Consejo de profesores':'Actividad de aniversario',body:role==='teacher'?'El consejo de profesores de esta semana se realizará en la sala de reuniones al finalizar la jornada.':'Durante esta semana se realizarán actividades de aniversario. Revisa la información entregada por tu profesor jefe.',audience:role==='teacher'?'teachers':'students',priority:'normal',active:true,createdAt:today,authorName:'Administración'}]}}
function ensureNav(){const nav=$('#nav');if(!nav)return;if(S.user?.role==='admin'&&!S.adminPreview&&!nav.querySelector('[data-page="admin-communications"]')){const b=document.createElement('button');b.type='button';b.className='nav-btn';b.dataset.page='admin-communications';b.innerHTML='<span class="nav-icon">✉</span><span>Comunicados</span>';const hist=nav.querySelector('[data-page="admin-history"]');nav.insertBefore(b,hist||null)}if(['student','teacher'].includes(S.user?.role)&&!S.adminPreview&&!nav.querySelector('[data-page="communications"]')){const b=document.createElement('button');b.type='button';b.className='nav-btn';b.dataset.page='communications';b.innerHTML='<span class="nav-icon">✉</span><span>Comunicados</span>';const hist=nav.querySelector(`[data-page="${S.user.role}-history"]`);nav.insertBefore(b,hist||null)}}
function ensurePreview(){const nav=$('#nav'),p=S.adminPreview;if(!nav||S.user?.role!=='admin'||!p||!['student','teacher'].includes(p.role)||nav.querySelector('[data-preview-communications]'))return;const b=document.createElement('button');b.type='button';b.className='nav-btn';b.setAttribute('data-preview-communications','');b.innerHTML='<span class="nav-icon">✉</span><span>Comunicados</span>';const hist=nav.querySelector('[data-preview-history]');nav.insertBefore(b,hist||null);b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();renderFeed({preview:true,sample:p.sample,role:p.role})},true)}
const baseShell=U.renderShell;U.renderShell=()=>{baseShell();ensureNav()};
const baseNavigate=U.navigate;U.navigate=async page=>{if(page==='admin-communications'){S.page=page;$('#content').innerHTML='<div class="card empty">Cargando comunicados…</div>';try{return await renderAdmin()}catch(e){$('#content').innerHTML=`<div class="card"><h2>No se pudieron cargar los comunicados</h2><p class="form-error">${U.esc(e.message)}</p></div>`;return}}if(page==='communications'){S.page=page;$('#content').innerHTML='<div class="card empty">Cargando comunicados…</div>';try{return await renderFeed()}catch(e){$('#content').innerHTML=`<div class="card"><h2>No se pudieron cargar los comunicados</h2><p class="form-error">${U.esc(e.message)}</p></div>`;return}}return baseNavigate(page)};
const nav=$('#nav');if(nav)new MutationObserver(()=>setTimeout(()=>{ensureNav();ensurePreview()},0)).observe(nav,{childList:true,subtree:false});document.addEventListener('click',()=>setTimeout(()=>{ensureNav();ensurePreview()},0),true);setTimeout(()=>{ensureNav();ensurePreview()},0);
})();
