(()=>{
const U=window.U,$=U.$,S=U.state;
const style=document.createElement('style');style.textContent=`
.export-head{display:flex;justify-content:space-between;align-items:flex-end;gap:16px;margin-bottom:18px}.export-head h1{margin:0 0 5px;font-size:30px;letter-spacing:-.8px}.export-head p{margin:0;color:var(--muted);max-width:760px}.export-filter{display:flex;align-items:center;gap:9px;background:var(--card);border:1px solid var(--line);border-radius:13px;padding:9px 11px}.export-filter label{font-size:10px;font-weight:800;color:var(--muted);white-space:nowrap}.export-filter select{min-width:180px;border:0;background:transparent;color:var(--text);font-weight:750;outline:0}.export-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.export-card{position:relative;overflow:hidden;background:var(--card);border:1px solid var(--line);border-radius:18px;padding:20px;box-shadow:var(--shadow-soft)}.export-card:before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--orange)}.export-card.blue:before{background:var(--blue)}.export-card.green:before{background:var(--green)}.export-icon{display:grid;place-items:center;width:42px;height:42px;border-radius:12px;background:var(--surface-soft);color:var(--blue);font-size:20px;font-weight:900;margin-bottom:14px}.export-card h2{margin:0 0 6px;font-size:17px}.export-card p{margin:0;color:var(--muted);font-size:11px;line-height:1.5;min-height:34px}.export-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:17px}.export-format{display:inline-flex;align-items:center;gap:7px}.export-format span{font-size:9px;font-weight:850;letter-spacing:.3px}.export-note{margin-top:16px;border:1px solid var(--line);border-left:4px solid var(--orange);border-radius:13px;background:var(--surface-soft);padding:13px 14px;color:var(--muted);font-size:10px;line-height:1.5}.export-modal-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.export-modal-card{border:1px solid var(--line);border-radius:14px;background:var(--surface-soft);padding:14px}.export-modal-card strong{display:block;font-size:12px;margin-bottom:4px}.export-modal-card p{margin:0;color:var(--muted);font-size:10px;line-height:1.4}.export-modal-actions{display:flex;gap:7px;margin-top:12px;flex-wrap:wrap}.export-badge{display:inline-block;border-radius:999px;padding:4px 7px;background:var(--orange-soft);color:var(--orange);font-size:8px;font-weight:850;margin-bottom:9px}
html[data-theme="dark"] .export-card,html[data-theme="dark"] .export-filter{background:var(--card)!important;border-color:var(--line)!important}html[data-theme="dark"] .export-modal-card,html[data-theme="dark"] .export-note{background:var(--surface-soft)!important;border-color:var(--line)!important}
@media(max-width:800px){.export-head{align-items:flex-start;flex-direction:column}.export-filter{width:100%}.export-filter select{min-width:0;flex:1}.export-grid{grid-template-columns:1fr}}@media(max-width:560px){.export-modal-grid{grid-template-columns:1fr}}
`;document.head.appendChild(style);

function startDownload(url){const a=document.createElement('a');a.href=url;a.style.display='none';document.body.appendChild(a);a.click();setTimeout(()=>a.remove(),500);U.toast('Preparando archivo…')}
function exportUrl(scope,kind,format,extra=''){return `/api/exports/${scope}/${kind}.${format}${extra}`}

U.renderAdminExports=async()=>{
  const d=S.admin||await U.api('/api/admin/overview');S.admin=d;
  U.setPage('Exportar',`Año escolar ${d.activeYear.year}`,'');
  document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page==='admin-exports'));
  $('#content').innerHTML=`
    <div class="export-head"><div><span class="eyebrow">Reportes</span><h1>Centro de exportación</h1><p>Genera documentos PDF listos para imprimir o archivos Excel para trabajar con la información académica del liceo.</p></div><div class="export-filter"><label>Filtrar por curso</label><select id="exportCourse"><option value="">Todos los cursos</option>${(d.courses||[]).filter(c=>c.active!==false).map(c=>`<option value="${c.id}">${U.esc(c.name)}</option>`).join('')}</select></div></div>
    <div class="export-grid">
      <article class="export-card blue"><div class="export-icon">◎</div><h2>Listado de estudiantes</h2><p>Nombres, RUT, curso y estado de las cuentas estudiantiles. El filtro de curso es opcional.</p><div class="export-actions"><button class="btn secondary export-format" data-export="students" data-format="pdf"><span>PDF</span> Descargar</button><button class="btn primary export-format" data-export="students" data-format="xlsx"><span>XLSX</span> Excel</button></div></article>
      <article class="export-card green"><div class="export-icon">✓</div><h2>Asistencia</h2><p>Resumen por estudiante con presentes, ausentes, registros acumulados y porcentaje de asistencia.</p><div class="export-actions"><button class="btn secondary export-format" data-export="attendance" data-format="pdf"><span>PDF</span> Descargar</button><button class="btn primary export-format" data-export="attendance" data-format="xlsx"><span>XLSX</span> Excel</button></div></article>
      <article class="export-card"><div class="export-icon">▤</div><span class="export-badge">Requiere elegir un curso</span><h2>Libro de notas por curso</h2><p>Incluye las asignaturas del curso, evaluaciones, ponderaciones, notas y promedios actuales.</p><div class="export-actions"><button class="btn secondary export-format" data-export="gradebook" data-format="pdf"><span>PDF</span> Descargar</button><button class="btn primary export-format" data-export="gradebook" data-format="xlsx"><span>XLSX</span> Excel</button></div></article>
      <article class="export-card blue"><div class="export-icon">▥</div><h2>Estadísticas administrativas</h2><p>Indicadores generales del año, asistencia, evaluaciones, promedios y resumen por curso.</p><div class="export-actions"><button class="btn secondary export-format" data-export="statistics" data-format="pdf"><span>PDF</span> Descargar</button><button class="btn primary export-format" data-export="statistics" data-format="xlsx"><span>XLSX</span> Excel</button></div></article>
    </div>
    <div class="export-note"><strong>Privacidad:</strong> los reportes se generan al momento usando la sesión iniciada. Profesores solo pueden exportar sus propias clases y estudiantes solo su información personal. Cada exportación queda registrada en el Registro de cambios.</div>`;
  $('#content').onclick=e=>{const b=e.target.closest('[data-export]');if(!b)return;const kind=b.dataset.export,format=b.dataset.format,courseId=$('#exportCourse')?.value||'';if(kind==='gradebook'&&!courseId){U.toast('Selecciona un curso para exportar el libro de notas');return}const extra=(kind==='statistics'||!courseId)?'':`?courseId=${encodeURIComponent(courseId)}`;startDownload(exportUrl('admin',kind,format,extra))};
};

function ensureAdminNav(){const nav=$('#nav');if(!nav||S.user?.role!=='admin'||S.adminPreview||nav.querySelector('[data-page="admin-exports"]'))return;const b=document.createElement('button');b.type='button';b.className='nav-btn';b.dataset.page='admin-exports';b.innerHTML='<span class="nav-icon">⇩</span><span>Exportar</span>';const audit=nav.querySelector('[data-page="admin-audit"]'),hist=nav.querySelector('[data-page="admin-history"]');if(audit)audit.before(b);else nav.insertBefore(b,hist||null)}
const shellBase=U.renderShell;U.renderShell=()=>{shellBase();ensureAdminNav()};
const navBase=U.navigate;U.navigate=async page=>{if(page!=='admin-exports')return navBase(page);S.page=page;$('#content').innerHTML='<div class="card empty">Cargando exportaciones…</div>';try{return await U.renderAdminExports()}catch(e){$('#content').innerHTML=`<div class="card"><h2>No se pudo abrir Exportar</h2><p class="form-error">${U.esc(e.message)}</p><button id="retryExports" class="btn ghost">Reintentar</button></div>`;$('#retryExports').onclick=()=>U.navigate('admin-exports')}};

function teacherExportModal(){const id=Number(S.currentAssignment?.assignment?.id);if(!id){U.toast('Abre una clase antes de exportar');return}const d=S.currentAssignment.assignment;U.openModal('Exportar clase',`<div class="export-modal-grid"><div class="export-modal-card"><strong>Libro de notas</strong><p>${U.esc(d.courseName)} · ${U.esc(d.subjectName)}. Incluye ambos semestres y las evaluaciones registradas.</p><div class="export-modal-actions"><button class="btn secondary" data-teacher-export="gradebook" data-format="pdf">PDF</button><button class="btn primary" data-teacher-export="gradebook" data-format="xlsx">Excel</button></div></div><div class="export-modal-card"><strong>Asistencia</strong><p>Resumen de presentes, ausentes y porcentaje por estudiante, con detalle de fechas en Excel.</p><div class="export-modal-actions"><button class="btn secondary" data-teacher-export="attendance" data-format="pdf">PDF</button><button class="btn primary" data-teacher-export="attendance" data-format="xlsx">Excel</button></div></div></div>`);$('#modalBody').onclick=e=>{const b=e.target.closest('[data-teacher-export]');if(!b)return;startDownload(`/api/exports/teacher/assignment/${id}/${b.dataset.teacherExport}.${b.dataset.format}`)}}
const teacherClassBase=U.renderTeacherClass;if(typeof teacherClassBase==='function')U.renderTeacherClass=async id=>{const out=await teacherClassBase(id);if(S.user?.role==='teacher'&&!S.adminPreview){const actions=$('#topActions');if(actions&&!$('#teacherExportBtn')){actions.insertAdjacentHTML('afterbegin','<button id="teacherExportBtn" class="btn secondary">⇩ Exportar</button>');$('#teacherExportBtn').onclick=teacherExportModal}}return out};

function studentExportModal(){U.openModal('Exportar mi reporte',`<div class="export-modal-grid"><div class="export-modal-card"><strong>Reporte académico personal</strong><p>Incluye tus datos del año actual, notas por materia y resumen de asistencia.</p><div class="export-modal-actions"><button class="btn secondary" data-student-export="pdf">PDF</button><button class="btn primary" data-student-export="xlsx">Excel</button></div></div><div class="export-modal-card"><strong>¿Qué formato elegir?</strong><p>PDF es mejor para guardar o imprimir. Excel permite ordenar y revisar los datos en una hoja de cálculo.</p></div></div>`);$('#modalBody').onclick=e=>{const b=e.target.closest('[data-student-export]');if(b)startDownload(`/api/exports/student/report.${b.dataset.studentExport}`)}}
const studentHomeBase=U.renderStudentHome;if(typeof studentHomeBase==='function')U.renderStudentHome=async(...args)=>{const out=await studentHomeBase(...args);if(S.user?.role==='student'&&!S.adminPreview){const actions=$('#topActions');if(actions&&!$('#studentExportBtn')){actions.insertAdjacentHTML('afterbegin','<button id="studentExportBtn" class="btn secondary">⇩ Exportar reporte</button>');$('#studentExportBtn').onclick=studentExportModal}}return out};

const nav=$('#nav');if(nav)new MutationObserver(()=>setTimeout(ensureAdminNav,0)).observe(nav,{childList:true});setTimeout(ensureAdminNav,0);
})();
