(()=>{
const U=window.U,$=U.$,S=U.state;
const style=document.createElement('style');style.textContent=`
.notify-bell{position:relative;display:inline-flex;align-items:center;justify-content:center;width:40px;height:40px;border-radius:12px;border:1px solid var(--line);background:var(--card);color:var(--text);font-size:18px;cursor:pointer;box-shadow:var(--shadow-soft)}.notify-bell:hover{transform:translateY(-1px)}.notify-count{position:absolute;right:-5px;top:-5px;min-width:19px;height:19px;padding:0 5px;border-radius:999px;display:grid;place-items:center;background:var(--orange);color:#fff;font-size:9px;font-weight:900;border:2px solid var(--card)}.notify-count[hidden]{display:none!important}.notify-list{display:grid;gap:8px;max-height:min(62vh,520px);overflow:auto;padding-right:2px}.notify-item{width:100%;display:grid;grid-template-columns:42px minmax(0,1fr) auto;gap:11px;align-items:flex-start;text-align:left;border:1px solid var(--line);border-radius:14px;background:var(--surface-soft);padding:12px;color:var(--text)}.notify-item.unread{background:linear-gradient(90deg,var(--orange-soft),var(--card) 28%);border-color:rgba(235,82,31,.28)}.notify-icon{width:38px;height:38px;border-radius:11px;display:grid;place-items:center;background:var(--blue-soft);color:var(--blue);font-weight:900}.notify-item.important .notify-icon{background:var(--orange-soft);color:var(--orange)}.notify-copy strong{display:block;font-size:12px;margin:1px 0 4px}.notify-copy p{margin:0;color:var(--muted);font-size:10px;line-height:1.45}.notify-time{font-size:8px;color:var(--muted);white-space:nowrap;margin-top:2px}.notify-dot{width:8px;height:8px;border-radius:99px;background:var(--orange);display:inline-block;margin-left:5px}.notify-toolbar{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:12px}.notify-toolbar span{color:var(--muted);font-size:10px}.notify-empty{padding:30px 14px;text-align:center;color:var(--muted);border:1px dashed var(--line);border-radius:14px}.notify-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:12px}
html[data-theme="dark"] .notify-bell{background:var(--card)!important;border-color:var(--line)!important}html[data-theme="dark"] .notify-item{background:var(--surface-soft)!important;border-color:var(--line)!important}html[data-theme="dark"] .notify-item.unread{background:linear-gradient(90deg,#2a1b17,var(--card) 28%)!important;border-color:#5c3527!important}.notify-bell:focus-visible{outline:3px solid rgba(7,55,90,.18)}
@media(max-width:650px){.notify-bell{width:38px;height:38px;flex:0 0 auto}.notify-item{grid-template-columns:38px 1fr}.notify-time{grid-column:2}}
`;document.head.appendChild(style);

let cache={unread:0,notifications:[]},loading=false,lastFetch=0;
const iconFor=t=>t==='grade'?'7':t==='evaluation'||t==='reminder'?'▣':t==='announcement'?'✉':'•';
const timeAgo=v=>{if(!v)return '';const ms=Date.now()-new Date(v).getTime(),m=Math.max(0,Math.floor(ms/60000));if(m<1)return 'ahora';if(m<60)return `hace ${m} min`;const h=Math.floor(m/60);if(h<24)return `hace ${h} h`;const d=Math.floor(h/24);return d===1?'ayer':`hace ${d} días`};
function bellHtml(){return `<button type="button" id="notificationBell" class="notify-bell" aria-label="Notificaciones" title="Notificaciones">♢<span id="notificationCount" class="notify-count" ${cache.unread?'':'hidden'}>${cache.unread>99?'99+':cache.unread}</span></button>`}
function ensureBell(){if(!S.user||S.adminPreview)return;const a=$('#topActions');if(!a||$('#notificationBell'))return;a.insertAdjacentHTML('beforeend',bellHtml());const b=$('#notificationBell');if(b)b.onclick=openNotifications}
function updateBadge(){const c=$('#notificationCount');if(c){c.textContent=cache.unread>99?'99+':cache.unread;c.hidden=!cache.unread}ensureBell()}
async function refresh(force=false){if(!S.user||S.adminPreview||loading)return cache;if(!force&&Date.now()-lastFetch<15000){updateBadge();return cache}loading=true;try{cache=await U.api('/api/notifications?limit=60');lastFetch=Date.now();updateBadge()}catch{}finally{loading=false}return cache}
function renderModal(){
  const items=cache.notifications||[];U.openModal('Notificaciones',`<div class="notify-toolbar"><span>${cache.unread?`${cache.unread} sin leer`:'Todo al día'}</span>${cache.unread?'<button type="button" id="notifyReadAll" class="btn small secondary">Marcar todas como leídas</button>':''}</div><div class="notify-list">${items.length?items.map(n=>`<button type="button" class="notify-item ${n.read?'':'unread'} ${n.priority==='important'?'important':''}" data-notification-id="${n.id}" data-notification-page="${U.esc(n.linkPage||'')}"><span class="notify-icon">${iconFor(n.type)}</span><span class="notify-copy"><strong>${U.esc(n.title)}${n.read?'':'<span class="notify-dot"></span>'}</strong><p>${U.esc(n.body)}</p></span><span class="notify-time">${U.esc(timeAgo(n.createdAt))}</span></button>`).join(''):'<div class="notify-empty"><strong>No tienes notificaciones.</strong><div style="margin-top:5px">Cuando haya novedades académicas aparecerán aquí.</div></div>'}</div><div class="notify-actions"><button type="button" class="btn ghost" data-close-notify>Cerrar</button></div>`);
  const close=$('[data-close-notify]');if(close)close.onclick=U.closeModal;const all=$('#notifyReadAll');if(all)all.onclick=markAll;
  const list=document.querySelector('.notify-list');if(list)list.onclick=async e=>{const b=e.target.closest('[data-notification-id]');if(!b)return;const id=Number(b.dataset.notificationId),page=b.dataset.notificationPage;try{const d=await U.api(`/api/notifications/${id}/read`,{method:'POST'});cache.unread=d.unread;const item=cache.notifications.find(x=>x.id===id);if(item)item.read=true;updateBadge();U.closeModal();if(page)U.navigate(page)}catch(err){U.toast(err.message)}};
}
async function openNotifications(){await refresh(true);renderModal()}
async function markAll(){try{await U.api('/api/notifications/read-all',{method:'POST'});cache.unread=0;cache.notifications.forEach(x=>x.read=true);updateBadge();renderModal()}catch(e){U.toast(e.message)}}

const baseSetPage=U.setPage;U.setPage=(...args)=>{baseSetPage(...args);setTimeout(()=>{ensureBell();refresh()},0)};
const baseShell=U.renderShell;U.renderShell=()=>{baseShell();setTimeout(()=>{ensureBell();refresh(true)},0)};
setInterval(()=>refresh(true),60000);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh(true)});
setTimeout(()=>{ensureBell();refresh(true)},200);
})();