(()=>{
const U=window.U,$=U.$,S=U.state;
const pad=n=>String(n).padStart(2,'0');
const schoolParts=(date=new Date())=>{const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date),get=t=>parts.find(p=>p.type===t)?.value;return {year:Number(get('year')),month:Number(get('month')),day:Number(get('day'))}};
const schoolToday=()=>{const p=schoolParts();return `${p.year}-${pad(p.month)}-${pad(p.day)}`};
const schoolMonth=()=>{const p=schoolParts();return `${p.year}-${pad(p.month)}`};

const style=document.createElement('style');style.id='undosUxSystem';style.textContent=`
:root{--ux-radius-sm:10px;--ux-radius:14px;--ux-radius-lg:18px;--ux-shadow:0 8px 28px rgba(16,38,59,.055);--ux-shadow-hover:0 16px 38px rgba(16,38,59,.10);--ux-blue-soft:rgba(7,55,90,.075);--ux-orange-soft:rgba(235,82,31,.09);--ux-green-soft:rgba(22,134,92,.09);--ux-red-soft:rgba(180,35,24,.08)}
html{scroll-behavior:smooth}body{letter-spacing:-.005em}.main{min-width:0}.content{max-width:1480px!important;padding-top:26px!important}
.content>.panel,.content>.card,.admin-home-grid>.panel,.admin-home-grid>.card,.student-stat,.student-detail,.teacher-stat-card,.teacher-course-card,.att-panel,.att-summary-card,.calendar-main,.calendar-side,.calendar-metric{border-top-color:var(--line)!important}
.card,.panel,.table-wrap,.stat,.student-stat,.student-subject-card,.student-detail,.history-card,.teacher-course-card,.teacher-stat-card,.att-panel,.att-summary-card,.calendar-main,.calendar-side,.student-cal-main,.student-cal-side,.comm-card,.comm-side,.profile-card,.dash-card{border-radius:var(--ux-radius-lg)!important;border-color:var(--line)!important;box-shadow:var(--ux-shadow)!important}
.card,.stat,.student-stat,.student-subject-card,.teacher-course-card,.att-summary-card{transition:transform .16s ease,box-shadow .16s ease,border-color .16s ease}button.card:hover,.student-subject-card:hover,.teacher-course-card:hover{transform:translateY(-2px)!important;box-shadow:var(--ux-shadow-hover)!important}
.topbar{height:76px!important;padding:0 30px!important;background:color-mix(in srgb,var(--bg) 88%,transparent)!important;border-bottom:1px solid var(--line)!important;backdrop-filter:blur(16px) saturate(120%)!important}.page-title strong{font-size:18px!important;font-weight:850!important;letter-spacing:-.35px!important}.page-title small{font-size:11px!important;margin-top:3px!important}.top-actions{gap:8px!important}
.welcome,.student-head,.calendar-intro,.student-cal-head,.comm-head{margin-bottom:22px!important}.welcome h1,.student-head h1,.calendar-intro h1,.student-cal-head h1,.comm-head h1{font-size:30px!important;letter-spacing:-1px!important;line-height:1.08!important}.eyebrow{font-size:10px!important;letter-spacing:.12em!important;font-weight:900!important}
.btn{min-height:38px;border-radius:11px!important;padding:9px 13px!important;font-size:12px!important;font-weight:800!important;display:inline-flex;align-items:center;justify-content:center;gap:7px;transition:transform .14s ease,box-shadow .14s ease,background .14s ease,border-color .14s ease}.btn.primary,.primary{background:linear-gradient(135deg,#07375a,#0b4d78)!important;box-shadow:0 8px 20px rgba(7,55,90,.14)!important}.btn.primary:hover,.primary:hover{transform:translateY(-1px)!important;box-shadow:0 11px 24px rgba(7,55,90,.20)!important}.btn.secondary,.secondary{background:var(--card)!important;border:1px solid color-mix(in srgb,var(--blue) 18%,var(--line))!important;color:var(--blue)!important}.btn.ghost,.ghost{background:transparent!important;border:1px solid var(--line)!important}.btn.danger{background:var(--ux-red-soft)!important}
.grid{gap:14px!important}.stat,.student-stat,.calendar-metric,.student-cal-stat,.comm-stat{position:relative;overflow:hidden;padding:17px 18px!important;min-height:104px!important;background:var(--card)!important}.stat:after,.student-stat:after,.calendar-metric:after,.student-cal-stat:after,.comm-stat:after{content:"";position:absolute;right:-18px;bottom:-24px;width:72px;height:72px;border-radius:50%;background:var(--ux-blue-soft);pointer-events:none}.stat strong,.student-stat strong,.calendar-metric strong,.student-cal-stat strong,.comm-stat strong{font-size:25px!important;letter-spacing:-.75px!important}.calendar-metric.warn:after,.comm-stat:nth-child(2):after{background:var(--ux-orange-soft)}
.table-wrap,.panel{overflow:auto!important;scrollbar-width:thin}table{border-collapse:separate!important;border-spacing:0!important}th{position:sticky;top:0;z-index:2;background:color-mix(in srgb,var(--card) 94%,var(--bg))!important;font-size:10px!important;letter-spacing:.07em!important;color:var(--muted)!important}th,td{padding:13px 14px!important}tbody tr{transition:background .12s ease}tbody tr:hover td{background:color-mix(in srgb,var(--blue) 3.5%,var(--card))!important}
input,select,textarea,.search,.semester{border-radius:11px!important;border-color:var(--line)!important;transition:border-color .14s,box-shadow .14s,background .14s}input:focus,select:focus,textarea:focus,.search:focus,.semester:focus{border-color:color-mix(in srgb,var(--blue) 55%,var(--line))!important;box-shadow:0 0 0 3px color-mix(in srgb,var(--blue) 10%,transparent)!important}.field label,.stack label{font-size:12px!important}.modal{border-radius:20px!important}.modal-head{padding:18px 20px!important}.modal-body{padding:20px!important}
.badge{border:1px solid transparent;border-radius:999px!important;padding:5px 9px!important;font-size:10px!important}.badge.blue{background:var(--ux-blue-soft)!important;color:var(--blue)!important}.badge.ok{background:var(--ux-green-soft)!important;color:var(--green)!important}.badge.warn{background:var(--ux-orange-soft)!important;color:var(--orange)!important}.badge.danger{background:var(--ux-red-soft)!important;color:var(--danger)!important}
.empty{border-style:dashed!important;background:color-mix(in srgb,var(--card) 88%,var(--bg))!important;min-height:120px;display:grid;place-items:center;align-content:center;gap:8px;line-height:1.5}.empty:before{content:"";width:34px;height:34px;border-radius:11px;background:var(--ux-blue-soft);display:block}.ux-loading-state{position:relative;overflow:hidden!important;color:transparent!important;min-height:140px!important}.ux-loading-state:before{content:"";width:48%;height:14px;border-radius:8px;background:var(--line);box-shadow:0 30px 0 var(--line),0 60px 0 var(--line);opacity:.72}.ux-loading-state:after{content:"";position:absolute;inset:0;transform:translateX(-100%);background:linear-gradient(90deg,transparent,rgba(255,255,255,.35),transparent);animation:uxShimmer 1.2s infinite}@keyframes uxShimmer{to{transform:translateX(100%)}}
.sidebar{width:auto!important;padding:18px 14px!important;background:color-mix(in srgb,var(--card) 97%,var(--bg))!important}.side-brand{margin:0 1px 13px!important;padding:8px 9px 15px!important;gap:11px!important}.side-brand img{width:58px!important;height:50px!important;flex:0 0 58px!important;padding:5px!important;object-fit:contain!important;object-position:center!important;background:#fff!important;border-radius:11px!important}.side-brand strong{font-size:21px!important}.side-brand small{font-size:9px!important;margin-top:4px!important}.sidebar nav{display:block}.nav-title{display:none!important}.ux-nav-group{padding:15px 11px 6px;color:var(--muted);font-size:9px;font-weight:900;text-transform:uppercase;letter-spacing:.11em;user-select:none}.ux-nav-group:first-of-type{padding-top:6px}.nav-btn{position:relative;min-height:44px!important;padding:8px 10px!important;margin:2px 0!important;border-radius:11px!important;color:var(--muted)!important;font-size:13px!important;font-weight:700!important;transition:background .14s,color .14s,transform .14s!important}.nav-btn:hover{transform:translateX(2px)!important;background:var(--ux-blue-soft)!important;color:var(--blue)!important}.nav-btn.active{background:var(--ux-blue-soft)!important;color:var(--blue)!important;font-weight:850!important}.nav-btn.active:before{content:""!important;position:absolute!important;left:0!important;top:10px!important;bottom:10px!important;width:3px!important;border-radius:0 6px 6px 0!important;background:var(--orange)!important}.nav-icon{width:30px!important;height:30px!important;display:grid!important;place-items:center!important;border-radius:9px!important;background:transparent!important;color:currentColor!important;flex:0 0 30px!important}.nav-icon svg{width:17px;height:17px;stroke:currentColor;stroke-width:1.9;fill:none;stroke-linecap:round;stroke-linejoin:round}.nav-btn.active .nav-icon{background:color-mix(in srgb,var(--blue) 11%,transparent)!important}.user-mini{border-top:1px solid var(--line)!important;padding:13px 8px 0!important}
.ux-bottom-nav{display:none;position:fixed;left:8px;right:8px;bottom:max(8px,env(safe-area-inset-bottom));z-index:95;background:color-mix(in srgb,var(--card) 94%,transparent);border:1px solid var(--line);border-radius:18px;box-shadow:0 14px 44px rgba(7,20,32,.18);backdrop-filter:blur(18px) saturate(135%);padding:5px}.ux-bottom-nav button{min-width:0;border:0;background:transparent;color:var(--muted);border-radius:13px;padding:7px 4px 6px;display:grid;place-items:center;gap:3px;font:inherit}.ux-bottom-nav button svg{width:19px;height:19px;stroke:currentColor;fill:none;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}.ux-bottom-nav button span{font-size:9px;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:100%}.ux-bottom-nav button.active{background:var(--ux-blue-soft);color:var(--blue)}.ux-bottom-nav button[data-more].active{color:var(--orange);background:var(--ux-orange-soft)}
.calendar-main,.student-cal-main{overflow:hidden!important}.calendar-toolbar,.student-cal-toolbar{background:color-mix(in srgb,var(--card) 96%,var(--bg))}.cal-event,.student-cal-event{transition:transform .12s,box-shadow .12s}.cal-event:hover,.student-cal-event:hover{transform:translateY(-1px);box-shadow:0 5px 14px rgba(7,55,90,.08)}
html[data-theme="dark"]{--ux-shadow:0 8px 28px rgba(0,0,0,.18);--ux-shadow-hover:0 16px 38px rgba(0,0,0,.26);--ux-blue-soft:rgba(110,182,223,.10);--ux-orange-soft:rgba(255,117,72,.10);--ux-green-soft:rgba(86,200,148,.10);--ux-red-soft:rgba(255,128,118,.10)}html[data-theme="dark"] .sidebar{background:#111821!important}html[data-theme="dark"] .topbar{background:rgba(13,19,27,.88)!important}html[data-theme="dark"] .ux-bottom-nav{background:rgba(17,24,33,.94)!important}html[data-theme="dark"] tbody tr:hover td{background:#19232e!important}html[data-theme="dark"] .empty{background:#111821!important}html[data-theme="dark"] .ux-loading-state:after{background:linear-gradient(90deg,transparent,rgba(255,255,255,.055),transparent)}
@media(max-width:1050px){.content{padding-left:20px!important;padding-right:20px!important}}
@media(max-width:820px){.ux-bottom-nav{display:grid;grid-template-columns:repeat(5,minmax(0,1fr))}.content{padding-bottom:96px!important}.sidebar.mobile-nav-open nav .ux-nav-group{grid-column:1/-1!important}.sidebar.mobile-nav-open nav{padding-bottom:14px!important}.topbar{padding-top:10px!important}.page-title strong{font-size:17px!important}}
@media(max-width:650px){.content{padding:8px 10px 100px!important}.topbar{padding:10px 10px 7px!important}.welcome h1,.student-head h1,.calendar-intro h1,.student-cal-head h1,.comm-head h1{font-size:24px!important}.welcome,.student-head,.calendar-intro,.student-cal-head,.comm-head{margin-bottom:15px!important}.card,.panel,.table-wrap,.student-stat,.student-subject-card,.student-detail,.calendar-main,.calendar-side{border-radius:14px!important}.stat,.student-stat,.calendar-metric,.student-cal-stat,.comm-stat{min-height:88px!important;padding:14px!important}.stat strong,.student-stat strong,.calendar-metric strong,.student-cal-stat strong,.comm-stat strong{font-size:22px!important}.btn{min-height:40px!important}.sidebar.mobile-nav-open nav{grid-template-columns:1fr!important}.ux-nav-group{padding-top:10px!important}.modal{width:calc(100% - 14px)!important;margin:7px!important}.modal-body{padding:15px!important}.table-wrap{border-radius:12px!important}.ux-bottom-nav{left:6px;right:6px;bottom:max(6px,env(safe-area-inset-bottom));border-radius:16px}.ux-bottom-nav button{padding-left:2px;padding-right:2px}.ux-bottom-nav button span{font-size:8px}}
`;document.head.appendChild(style);

const order={student:['student-home','student-dashboard','student-attendance','student-calendar','communications','student-profile','student-history'],teacher:['teacher-home','teacher-dashboard','teacher-calendar','teacher-planning','communications','teacher-history'],admin:['admin-home','admin-dashboard','admin-search','admin-users','admin-courses','admin-subjects','admin-communications','admin-statistics','admin-promotion','admin-exports','admin-audit','admin-years','admin-history']};
const groups={student:{'student-home':'Principal','student-dashboard':'Principal','student-attendance':'Académico','student-calendar':'Académico','communications':'Comunidad','student-profile':'Cuenta','student-history':'Cuenta'},teacher:{'teacher-home':'Principal','teacher-dashboard':'Principal','teacher-calendar':'Docencia','teacher-planning':'Docencia','communications':'Comunidad','teacher-history':'Cuenta'},admin:{'admin-home':'Principal','admin-dashboard':'Principal','admin-search':'Principal','admin-users':'Gestión académica','admin-courses':'Gestión académica','admin-subjects':'Gestión académica','admin-years':'Gestión académica','admin-communications':'Comunidad','admin-statistics':'Seguimiento','admin-promotion':'Seguimiento','admin-exports':'Reportes','admin-audit':'Sistema','admin-history':'Sistema'}};
const labels={'student-home':'Inicio','student-dashboard':'Dashboard','student-attendance':'Asistencia','student-calendar':'Calendario','communications':'Comunicados','student-profile':'Mi perfil','student-history':'Historial','teacher-home':'Clases','teacher-dashboard':'Dashboard','teacher-calendar':'Calendario','teacher-planning':'Planificación','teacher-history':'Historial','admin-home':'Resumen','admin-dashboard':'Dashboard','admin-search':'Buscar','admin-users':'Usuarios','admin-courses':'Cursos','admin-subjects':'Materias','admin-communications':'Comunicados','admin-statistics':'Estadísticas','admin-promotion':'Promoción','admin-exports':'Exportar','admin-audit':'Cambios','admin-years':'Años','admin-history':'Historial'};
const iconPaths={home:'<path d="M3 10.5 12 3l9 7.5"/><path d="M5.5 9.5V21h13V9.5"/><path d="M9 21v-7h6v7"/>',dashboard:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>',attendance:'<path d="m5 12 4 4L19 6"/><circle cx="12" cy="12" r="9"/>',messages:'<path d="M4 5h16v12H7l-3 3V5Z"/><path d="M8 9h8M8 13h5"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',history:'<path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/>',classes:'<path d="M4 5h16v14H4z"/><path d="M8 2v6M16 2v6M4 10h16"/>',planning:'<path d="M5 3h14v18H5z"/><path d="M9 7h6M9 11h6M9 15h4"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/>',courses:'<path d="M4 4h16v16H4z"/><path d="M4 9h16M9 4v16"/>',subjects:'<path d="m3 6 9-3 9 3-9 3-9-3Z"/><path d="m6 10 6 2 6-2v6l-6 2-6-2v-6Z"/>',stats:'<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/>',promotion:'<path d="M12 19V5M6 11l6-6 6 6"/><path d="M5 21h14"/>',export:'<path d="M12 3v12M7 10l5 5 5-5"/><path d="M5 21h14"/>',audit:'<path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>',years:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>'};
const pageIcon=page=>page.includes('dashboard')?'dashboard':page.includes('calendar')?'calendar':page.includes('attendance')?'attendance':page.includes('communication')||page==='communications'?'messages':page.includes('profile')?'user':page.includes('history')?'history':page==='teacher-home'?'classes':page.includes('planning')?'planning':page.includes('search')?'search':page.includes('users')?'users':page.includes('courses')?'courses':page.includes('subjects')?'subjects':page.includes('statistics')?'stats':page.includes('promotion')?'promotion':page.includes('exports')?'export':page.includes('audit')?'audit':page.includes('years')?'years':'home';
const svg=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${iconPaths[name]||iconPaths.home}</svg>`;
function normalizeNav(){if(!S.user||S.adminPreview)return;const nav=$('#nav'),wanted=order[S.user.role];if(!nav||!wanted)return;let anchor=nav.querySelector('.nav-title');for(const page of wanted){const el=nav.querySelector(`[data-page="${page}"]`);if(!el)continue;if(anchor?.nextElementSibling!==el)anchor.after(el);anchor=el}}
function decorateNav(){const nav=$('#nav');if(!nav||!S.user||S.adminPreview)return;normalizeNav();nav.querySelectorAll('.ux-nav-group').forEach(x=>x.remove());let last='';for(const page of order[S.user.role]||[]){const btn=nav.querySelector(`[data-page="${page}"]`);if(!btn)continue;const group=groups[S.user.role]?.[page]||'';if(group&&group!==last){const h=document.createElement('div');h.className='ux-nav-group';h.textContent=group;btn.before(h);last=group}const icon=btn.querySelector('.nav-icon');if(icon)icon.innerHTML=svg(pageIcon(page));const text=btn.querySelector('span:last-child');if(text&&labels[page])text.textContent=labels[page];btn.setAttribute('aria-label',labels[page]||page);btn.setAttribute('aria-current',S.page===page?'page':'false')}syncBottomNav()}
const mobilePrimary={student:['student-home','student-attendance','student-calendar','communications'],teacher:['teacher-home','teacher-calendar','teacher-planning','communications'],admin:['admin-home','admin-search','admin-users','admin-statistics']};
function ensureBottomNav(){let dock=$('#uxBottomNav');if(S.adminPreview||!S.user){dock?.remove();return}if(!dock){dock=document.createElement('nav');dock.id='uxBottomNav';dock.className='ux-bottom-nav';dock.setAttribute('aria-label','Navegación rápida');document.body.appendChild(dock)}const pages=mobilePrimary[S.user.role]||[],key=`${S.user.role}:${pages.join(',')}`;if(dock.dataset.key!==key){dock.dataset.key=key;dock.innerHTML=pages.map(page=>`<button type="button" data-ux-page="${page}" aria-label="${labels[page]||page}">${svg(pageIcon(page))}<span>${labels[page]||page}</span></button>`).join('')+`<button type="button" data-more aria-label="Más opciones">${svg('more')}<span>Más</span></button>`;dock.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-more')){const side=$('.sidebar'),toggle=$('#mobileNavToggle');if(side){side.classList.add('mobile-nav-open');toggle?.setAttribute('aria-expanded','true');if(toggle){toggle.textContent='×';toggle.setAttribute('aria-label','Cerrar menú')}}return}const page=b.dataset.uxPage;if(page)U.navigate(page)}}syncBottomNav()}
function syncBottomNav(){const dock=$('#uxBottomNav');if(!dock)return;const pages=mobilePrimary[S.user?.role]||[],primary=pages.includes(S.page);dock.querySelectorAll('[data-ux-page]').forEach(b=>b.classList.toggle('active',b.dataset.uxPage===S.page));dock.querySelector('[data-more]')?.classList.toggle('active',!!S.page&&!primary)}
function polishStudentCalendar(){const d=S.studentCalendar;if(!d||!$('#studentCalGrid'))return;const today=schoolToday(),future=(d.evaluations||[]).filter(e=>e.date>=today).sort((a,b)=>a.date.localeCompare(b.date)||String(a.subjectName||'').localeCompare(String(b.subjectName||''),'es'));const stats=[...document.querySelectorAll('.student-cal-stat')];if(stats[1]){const l=stats[1].querySelector('small'),v=stats[1].querySelector('strong');if(l)l.textContent='Próximas en este mes';if(v)v.textContent=String(future.length)}const side=$('.student-cal-side');if(side){const head=side.querySelector('.student-cal-side-head');if(head){const h=head.querySelector('h2'),p=head.querySelector('p');if(h)h.textContent='Evaluaciones restantes del mes';if(p)p.textContent='Fechas pendientes dentro del mes que estás revisando.'}side.querySelectorAll('.student-upcoming,.empty').forEach(x=>x.remove());side.insertAdjacentHTML('beforeend',future.length?future.slice(0,10).map(e=>`<div class="student-upcoming"><div class="date">${U.fmtDate(e.date)}</div><strong>${U.esc(e.name)}</strong><small>${U.esc(e.subjectName)} · Prof. ${U.esc(e.teacherName||'—')} · ${Number(e.weight)}%</small></div>`).join(''):'<div class="empty">No quedan evaluaciones en este mes.</div>')}const days=[...document.querySelectorAll('.student-cal-day')];days.forEach(x=>x.classList.remove('today'));const [y,m]=String(d.month||'').split('-').map(Number),p=schoolParts();if(y===p.year&&m===p.month&&days.length){const firstDow=(new Date(Date.UTC(y,m-1,1)).getUTCDay()+6)%7,idx=firstDow+p.day-1;if(days[idx])days[idx].classList.add('today')}}
function polishDashboard(){const d=S.dashboard;if(d?.role!=='student')return;[...document.querySelectorAll('.dash-subject')].forEach((row,i)=>{const subject=d.subjects?.[i],bar=row.querySelector('.dash-mini-progress i');if(!subject||!bar)return;const ap=Math.max(0,Math.min(100,Number(subject.attendancePercentage||0)));bar.style.width=`${ap}%`;bar.title=subject.attendancePercentage==null?'Sin asistencia registrada':`${Number(subject.attendancePercentage).toFixed(1)}% de asistencia`})}
function markLoading(){const c=$('#content');if(!c)return;const empty=c.querySelector('.card.empty');if(empty&&/^\s*Cargando/i.test(empty.textContent||''))empty.classList.add('ux-loading-state')}
const routedNavigate=U.navigate;U.navigate=async page=>{S.page=page;syncBottomNav();if(page==='student-calendar'){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const c=$('#content');if(c)c.innerHTML='<div class="card empty">Cargando calendario…</div>';markLoading();try{if(typeof U.renderStudentCalendar!=='function')throw new Error('El calendario del estudiante no terminó de cargar.');return await U.renderStudentCalendar(S.studentCalendarMonth||schoolMonth())}catch(e){if(c)c.innerHTML=`<div class="card"><h2>No se pudo cargar el calendario</h2><p class="form-error">${U.esc(e.message)}</p><button class="btn ghost" id="uxCalRetry">Reintentar</button></div>`;$('#uxCalRetry')?.addEventListener('click',()=>U.navigate(page));return}}if(page==='teacher-calendar'){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const c=$('#content');if(c)c.innerHTML='<div class="card empty">Cargando calendario docente…</div>';markLoading();try{if(typeof U.renderTeacherCalendar!=='function')throw new Error('El calendario docente no terminó de cargar.');return await U.renderTeacherCalendar(S.teacherCalendarMonth||schoolMonth())}catch(e){if(c)c.innerHTML=`<div class="card"><h2>No se pudo cargar el calendario docente</h2><p class="form-error">${U.esc(e.message)}</p><button class="btn ghost" id="uxCalRetry">Reintentar</button></div>`;$('#uxCalRetry')?.addEventListener('click',()=>U.navigate(page));return}}return routedNavigate(page)};
const baseShell=U.renderShell;U.renderShell=()=>{baseShell();setTimeout(()=>{decorateNav();ensureBottomNav()},0)};
if(typeof U.renderStudentCalendar==='function'){const base=U.renderStudentCalendar;U.renderStudentCalendar=async(...args)=>{const out=await base(...args);polishStudentCalendar();decorateNav();return out}}
if(typeof U.renderDashboard==='function'){const base=U.renderDashboard;U.renderDashboard=async(...args)=>{const out=await base(...args);polishDashboard();decorateNav();return out}}
const nav=$('#nav');if(nav)new MutationObserver(()=>setTimeout(()=>{decorateNav();ensureBottomNav()},0)).observe(nav,{childList:true,subtree:false});
document.addEventListener('click',e=>{if(S.user?.role==='student'&&!S.adminPreview&&e.target.closest('[data-student-cal-today]')&&S.studentCalendar?.month!==schoolMonth()){e.preventDefault();e.stopImmediatePropagation();U.renderStudentCalendar(schoolMonth())}setTimeout(syncBottomNav,0)},true);
const content=$('#content');if(content)new MutationObserver(()=>setTimeout(()=>{decorateNav();ensureBottomNav();markLoading();if(S.page==='student-calendar')polishStudentCalendar();if(S.page==='student-dashboard')polishDashboard()},0)).observe(content,{childList:true,subtree:false});
window.addEventListener('resize',ensureBottomNav,{passive:true});setTimeout(()=>{decorateNav();ensureBottomNav();markLoading()},0);
})();
