const express=require('express');
const bcrypt=require('bcryptjs');
const {pool,normalizeRut,validateRut}=require('./db');
const {apiError,setSession,clearSession,auth}=require('./auth');
const r=express.Router();
const loginAttempts=new Map(),WINDOW_MS=10*60*1000,MAX_ATTEMPTS=10;
const clientKey=req=>req.ip||req.socket.remoteAddress||'unknown';
function pruneAttempts(now=Date.now()){for(const [key,times] of loginAttempts){const fresh=times.filter(t=>now-t<WINDOW_MS);if(fresh.length)loginAttempts.set(key,fresh);else loginAttempts.delete(key)}}
function limited(req){const key=clientKey(req),now=Date.now(),a=(loginAttempts.get(key)||[]).filter(t=>now-t<WINDOW_MS);a.push(now);loginAttempts.set(key,a);if(loginAttempts.size>2000)pruneAttempts(now);return a.length>MAX_ATTEMPTS}
function clearLimit(req){loginAttempts.delete(clientKey(req))}
const cleanup=setInterval(()=>pruneAttempts(),WINDOW_MS);if(typeof cleanup.unref==='function')cleanup.unref();
r.get('/setup/status',async(_q,res)=>{try{const {rows}=await pool.query("SELECT COUNT(*)::int count FROM users WHERE role='admin'");res.json({needsSetup:rows[0].count===0})}catch(e){console.error(e);apiError(res,500,'No se pudo comprobar la configuración inicial')}});
r.post('/setup/admin',async(req,res)=>{const c=await pool.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(20260827)');const count=await c.query("SELECT COUNT(*)::int count FROM users WHERE role='admin'");if(count.rows[0].count>0){await c.query('ROLLBACK');return apiError(res,409,'La configuración inicial ya fue completada')}if(!process.env.SETUP_CODE||String(req.body.setupCode||'')!==process.env.SETUP_CODE){await c.query('ROLLBACK');return apiError(res,403,'Código de configuración incorrecto')}const rut=normalizeRut(req.body.rut),fullName=String(req.body.fullName||'').trim(),password=String(req.body.password||'');if(!validateRut(rut)){await c.query('ROLLBACK');return apiError(res,400,'El RUT no es válido')}if(!fullName){await c.query('ROLLBACK');return apiError(res,400,'Falta el nombre')}if(password.length<8){await c.query('ROLLBACK');return apiError(res,400,'La contraseña debe tener al menos 8 caracteres')}const hash=await bcrypt.hash(password,12),{rows}=await c.query("INSERT INTO users(rut,full_name,password_hash,role) VALUES($1,$2,$3,'admin') RETURNING id,rut,full_name,role",[rut,fullName,hash]);await c.query('COMMIT');setSession(res,rows[0]);res.status(201).json({user:{id:rows[0].id,rut:rows[0].rut,fullName:rows[0].full_name,role:rows[0].role}})}catch(e){await c.query('ROLLBACK').catch(()=>{});console.error(e);apiError(res,500,'No se pudo crear el administrador inicial')}finally{c.release()}});
r.post('/auth/login',async(req,res)=>{try{if(limited(req))return apiError(res,429,'Demasiados intentos. Espera unos minutos e inténtalo nuevamente.');const rut=normalizeRut(req.body.rut),password=String(req.body.password||'');if(!validateRut(rut)||!password)return apiError(res,400,'RUT o contraseña inválidos');const {rows}=await pool.query('SELECT * FROM users WHERE rut=$1 LIMIT 1',[rut]),u=rows[0];if(!u||!u.active||!(await bcrypt.compare(password,u.password_hash)))return apiError(res,401,'RUT o contraseña incorrectos');clearLimit(req);setSession(res,u);res.json({user:{id:u.id,rut:u.rut,fullName:u.full_name,role:u.role}})}catch(e){console.error(e);apiError(res,500,'No se pudo iniciar sesión')}});
r.post('/auth/logout',(_q,res)=>{clearSession(res);res.json({ok:true})});
r.get('/auth/me',auth,(req,res)=>res.json({user:{id:req.user.id,rut:req.user.rut,fullName:req.user.full_name,role:req.user.role}}));
module.exports=r;
