const express=require('express');
const path=require('path');
const {pool,initDatabase}=require('./db');
const {auth}=require('./auth');
const app=express(),PORT=Number(process.env.PORT||3000);
app.set('trust proxy',1);
app.disable('x-powered-by');
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Resource-Policy','same-origin');if(process.env.NODE_ENV==='production')res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");next()});
app.use(express.json({limit:'1mb'}));
app.use(express.urlencoded({extended:false,limit:'1mb'}));
const PUBLIC_FILES=new Set(['/styles.css','/polish.css','/teacher-polish.css','/theme.css','/core.js','/admin.js','/admin-enhancements.js','/admin-v2.js','/admin-course-tools.js','/admin-statistics.js','/admin-promotion.js','/admin-audit.js','/admin-global-search.js','/exports.js','/notifications.js','/dashboard.js','/review-fixes.js','/mobile-fixes.js','/calendar-router-fix.js','/home-experience.js','/teacher.js','/teacher-calendar.js','/teacher-planning.js','/student.js','/student-attendance.js','/student-calendar.js','/student-home-smart.js','/student-profile.js','/communications.js','/visual-fixes.js','/history.js','/attendance.js','/preview-sync.js','/theme.js','/logo.png','/logo.svg']);
app.get([...PUBLIC_FILES],(req,res)=>{res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate');res.setHeader('Pragma','no-cache');res.setHeader('Expires','0');res.sendFile(path.join(__dirname,req.path))});
app.use('/api',require('./routes-auth'));
app.use('/api',require('./routes-notification-hooks'));
app.use('/api/notifications',require('./routes-notifications'));
app.use('/api/dashboard',require('./routes-dashboard'));
app.use('/api/communications',require('./routes-communications'));
app.use('/api/exports',require('./routes-export-integrity'));
app.use('/api/exports',require('./routes-exports'));
app.use('/api/admin/preview',require('./routes-admin-preview-profile'));
app.use('/api/admin/preview',require('./routes-admin-preview-planbook'));
app.use('/api/admin/preview',require('./routes-admin-preview-calendar'));
app.use('/api/admin/preview',require('./routes-admin-preview-attendance'));
app.use('/api/admin/preview',require('./routes-admin-preview-planning'));
app.use('/api/admin/preview',require('./routes-admin-preview'));
app.use('/api/admin',require('./routes-admin-search'));
app.use('/api/admin',require('./routes-admin-audit'));
app.use('/api/admin',require('./routes-admin-promotion'));
app.use('/api/admin',require('./routes-admin-statistics'));
app.use('/api/admin',require('./routes-admin-integrity'));
app.use('/api/admin',require('./routes-admin-courses'));
app.use('/api/admin',require('./routes-admin'));
app.use('/api/teacher',require('./routes-teacher-planbook'));
app.use('/api/teacher',require('./routes-teacher-planning'));
app.use('/api/teacher',require('./routes-teacher'));
app.use('/api/student',require('./routes-student-profile'));
app.use('/api/student',require('./routes-student-calendar'));
app.use('/api/student',require('./routes-student-attendance'));
app.use('/api/student',require('./routes-student'));
app.use('/api/history',require('./routes-history'));
app.get('/api/history',auth,async(_q,res)=>{try{const {rows}=await pool.query('SELECT id,year,active FROM academic_years ORDER BY year DESC');res.json({years:rows})}catch{res.status(500).json({error:'No se pudo cargar el historial'})}});
app.get('/health',async(_q,res)=>{try{await pool.query('SELECT 1');res.type('text/plain').send('ok')}catch{res.status(503).type('text/plain').send('db unavailable')}});
app.get('*',(_q,res)=>{res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate');res.sendFile(path.join(__dirname,'index.html'))});
(async()=>{for(let i=1;i<=20;i++){try{await initDatabase();app.listen(PORT,'0.0.0.0',()=>console.log(`UnDos listo en puerto ${PORT}`));return}catch(e){console.error(`DB intento ${i}/20:`,e.message);if(i===20)process.exit(1);await new Promise(r=>setTimeout(r,3000))}}})();