const express=require('express');
const path=require('path');
const {pool,initDatabase}=require('./db');
const {auth}=require('./auth');
const app=express(),PORT=Number(process.env.PORT||3000);
app.set('trust proxy',1);
app.disable('x-powered-by');
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");next()});
app.use(express.json({limit:'1mb'}));
app.use(express.urlencoded({extended:false,limit:'1mb'}));
const PUBLIC_FILES=new Set(['/styles.css','/core.js','/admin.js','/admin-enhancements.js','/admin-v2.js','/teacher.js','/student.js','/logo.png','/logo.svg']);
app.get([...PUBLIC_FILES],(req,res)=>{res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate');res.setHeader('Pragma','no-cache');res.setHeader('Expires','0');res.sendFile(path.join(__dirname,req.path))});
app.use('/api',require('./routes-auth'));
app.use('/api/admin/preview',require('./routes-admin-preview'));
app.use('/api/admin',require('./routes-admin'));
app.use('/api/teacher',require('./routes-teacher'));
app.use('/api/student',require('./routes-student'));
app.get('/api/history',auth,async(_q,res)=>{try{const {rows}=await pool.query('SELECT id,year,active FROM academic_years ORDER BY year DESC');res.json({years:rows})}catch{res.status(500).json({error:'No se pudo cargar el historial'})}});
app.get('/health',async(_q,res)=>{try{await pool.query('SELECT 1');res.type('text/plain').send('ok')}catch{res.status(503).type('text/plain').send('db unavailable')}});
app.get('*',(_q,res)=>{res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate');res.sendFile(path.join(__dirname,'index.html'))});
(async()=>{for(let i=1;i<=20;i++){try{await initDatabase();app.listen(PORT,'0.0.0.0',()=>console.log(`UnDos listo en puerto ${PORT}`));return}catch(e){console.error(`DB intento ${i}/20:`,e.message);if(i===20)process.exit(1);await new Promise(r=>setTimeout(r,3000))}}})();
