(()=>{
const U=window.U;if(!U)return;const S=U.state,$=U.$;
const style=document.createElement('style');style.id='undosWorkspacePolish';style.textContent=`
/* UnDos · pasada final de historial, asistencia, dashboard y gestión */
.ux-section-tools{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin:0 0 14px;padding:12px 13px;background:var(--card);border:1px solid var(--line);border-radius:14px;box-shadow:var(--ux-shadow)}
.ux-section-tools-copy strong{display:block;font-size:12px}.ux-section-tools-copy small{display:block;margin-top:3px;color:var(--muted);font-size:9px}.ux-filter-row{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.ux-filter-row .search{min-width:220px;max-width:360px}.ux-filter-chip{border:1px solid var(--line);background:var(--surface-soft);color:var(--muted);border-radius:999px;padding:7px 10px;font-size:10px;font-weight:800;cursor:pointer}.ux-filter-chip.active{background:var(--ux-blue-soft);border-color:color-mix(in srgb,var(--blue) 24%,var(--line));color:var(--blue)}
.ux-manage-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-bottom:14px}.ux-manage-stat{position:relative;overflow:hidden;background:var(--card);border:1px solid var(--line);border-radius:15px;padding:14px 15px;box-shadow:var(--ux-shadow)}.ux-manage-stat:after{content:"";position:absolute;width:56px;height:56px;border-radius:50%;right:-17px;bottom:-20px;background:var(--ux-blue-soft)}.ux-manage-stat.orange:after{background:var(--ux-orange-soft)}.ux-manage-stat.green:after{background:var(--ux-green-soft)}.ux-manage-stat span{display:block;color:var(--muted);font-size:9px;font-weight:800}.ux-manage-stat strong{display:block;margin-top:5px;font-size:21px;letter-spacing:-.5px}.ux-manage-grid{position:relative}.ux-manage-grid [data-ux-managed-card]{transition:opacity .14s,transform .14s}
.history-card{position:relative;overflow:hidden}.history-card:after{content:"Abrir detalle";position:absolute;right:14px;bottom:12px;color:var(--muted);font-size:8px;font-weight:800;opacity:0;transition:.15s}.history-card:hover:after,.history-card.ux-selected:after{opacity:1}.history-card.ux-selected{border-color:color-mix(in srgb,var(--blue) 34%,var(--line))!important;box-shadow:0 10px 30px color-mix(in srgb,var(--blue) 10%,transparent)!important;background:color-mix(in srgb,var(--card) 97%,var(--blue))!important}.history-card.ux-selected:before{content:"";position:absolute;left:0;top:12px;bottom:12px;width:3px;border-radius:0 4px 4px 0;background:var(--orange)}.history-detail{scroll-margin-top:100px}.history-metric{border:1px solid transparent}.history-card.ux-selected .history-metric{background:var(--card);border-color:var(--line)}
.ux-history-tip{display:flex;align-items:flex-start;gap:10px;margin:0 0 14px;padding:11px 12px;border:1px solid var(--line);border-radius:13px;background:var(--surface-soft);color:var(--muted);font-size:10px;line-height:1.45}.ux-history-tip span{width:25px;height:25px;display:grid;place-items:center;flex:0 0 25px;border-radius:8px;background:var(--ux-blue-soft);color:var(--blue);font-weight:900}
.ux-att-controls{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.ux-att-count{color:var(--muted);font-size:9px;font-weight:800;margin-left:auto}.student-att-card-head.ux-with-filter{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.student-att-subject{transition:background .14s}.student-att-subject:hover{background:color-mix(in srgb,var(--blue) 3%,var(--card))}.student-att-progress span{transition:width .35s ease}.student-att-state{min-width:82px;justify-content:center}.student-att-table tbody tr[hidden]{display:none!important}
.ux-dash-actions{display:flex;gap:8px;flex-wrap:wrap;margin:-3px 0 14px}.ux-dash-actions .btn{min-height:34px!important}.dash-panel{transition:box-shadow .16s,border-color .16s}.dash-panel:hover{box-shadow:var(--ux-shadow-hover)!important;border-color:color-mix(in srgb,var(--blue) 12%,var(--line))!important}.dash-panel-head{background:color-mix(in srgb,var(--card) 97%,var(--bg))}.dash-stat{min-height:98px}.dash-stat strong{font-size:23px!important}.dash-list .dash-item{transition:background .13s}.dash-list .dash-item:hover{background:color-mix(in srgb,var(--blue) 3%,var(--card))}.dash-course{transition:transform .14s,border-color .14s}.dash-course:hover{transform:translateY(-1px);border-color:color-mix(in srgb,var(--blue) 18%,var(--line))}
html[data-theme="dark"] .history-card.ux-selected{background:color-mix(in srgb,var(--card) 94%,#1e4f70)!important}.ux-no-results{padding:24px;border:1px dashed var(--line);border-radius:14px;text-align:center;color:var(--muted);font-size:11px;background:var(--surface-soft)}
@media(max-width:820px){.ux-section-tools{align-items:stretch;flex-direction:column}.ux-filter-row{width:100%;display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.ux-filter-row .search{grid-column:1/-1;min-width:0;max-width:none;width:100%}.ux-manage-summary{grid-template-columns:repeat(3,1fr)}.history-card:after{display:none}.ux-dash-actions{display:grid;grid-template-columns:1fr 1fr}.ux-dash-actions .btn{width:100%}}
@media(max-width:560px){.ux-manage-summary{grid-template-columns:1fr}.ux-filter-row{grid-template-columns:1fr 1fr}.ux-filter-chip{width:100%}.student-att-card-head.ux-with-filter{align-items:flex-start;flex-direction:column}.ux-att-controls{width:100%;display:grid;grid-template-columns:repeat(3,1fr)}.ux-att-count{grid-column:1/-1;margin:0}.ux-dash-actions{grid-template-columns:1fr}.history-grid{gap:10px!important}.history-card{padding:15px!important}.history-metrics{gap:6px!important}.history-metric{padding:8px!important}}
`;document.head.appendChild(style);

const escapeAttr=s=>String(s??'').toLowerCase();
function summaryHtml(items){return `<div class="ux-manage-summary">${items.map((x,i)=>`<div class="ux-manage-stat ${i===1?'green':i===2?'orange':''}"><span>${U.esc(x[0])}</span><strong>${U.esc(String(x[1]))}</strong></div>`).join('')}</div>`}
function insertBeforeFirst(selector,html){const c=$('#content'),target=c?.querySelector(selector);if(target&&!c.querySelector('.ux-manage-summary'))target.insertAdjacentHTML('beforebegin',html)}
function noResults(container,show){let el=container?.querySelector(':scope > .ux-no-results');if(show&&!el){el=document.createElement('div');el.className='ux-no-results';el.textContent='No hay resultados con estos filtros.';container.appendChild(el)}else if(!show&&el)el.remove()}

function enhanceAdminUsers(){
  if(S.page!=='admin-users'||S.user?.role!=='admin'||S.adminPreview)return;const c=$('#content');if(!c||c.dataset.uxUsers==='1')return;c.dataset.uxUsers='1';
  const users=S.admin?.users||[],active=users.filter(u=>u.active).length,students=users.filter(u=>u.active&&u.role==='student').length,teachers=users.filter(u=>u.active&&u.role==='teacher').length;
  const card=c.querySelector('.card');if(card)card.insertAdjacentHTML('beforebegin',summaryHtml([['Usuarios activos',active],['Estudiantes',students],['Profesores',teachers]]));
  const table=c.querySelector('table'),rows=[...(table?.querySelectorAll('tbody tr')||[])];if(!table||!rows.length)return;
  rows.forEach((r,i)=>{const u=users[i];if(u){r.dataset.uxRole=u.role;r.dataset.uxStatus=u.active?'active':'inactive';r.dataset.uxSearch=escapeAttr(`${u.fullName} ${U.fmtRut(u.rut)} ${u.courseName||''}`)}});
  const tools=document.createElement('div');tools.className='ux-section-tools';tools.innerHTML='<div class="ux-section-tools-copy"><strong>Encuentra una cuenta rápidamente</strong><small>Filtra por nombre, RUT, rol o estado sin salir de esta sección.</small></div><div class="ux-filter-row"><input class="search" id="uxUserSearch" placeholder="Buscar nombre, RUT o curso"><button class="ux-filter-chip active" data-ux-role="all">Todos</button><button class="ux-filter-chip" data-ux-role="student">Estudiantes</button><button class="ux-filter-chip" data-ux-role="teacher">Profesores</button><button class="ux-filter-chip" data-ux-role="admin">Administradores</button><button class="ux-filter-chip" data-ux-status="inactive">Inactivos</button></div>';
  card?.before(tools);let role='all',onlyInactive=false;const apply=()=>{const q=escapeAttr($('#uxUserSearch')?.value);let shown=0;rows.forEach(r=>{const okQ=!q||r.dataset.uxSearch.includes(q),okR=role==='all'||r.dataset.uxRole===role,okS=!onlyInactive||r.dataset.uxStatus==='inactive';r.hidden=!(okQ&&okR&&okS);if(!r.hidden)shown++});noResults(table.closest('.table-wrap')||card,shown===0)};
  $('#uxUserSearch').oninput=apply;tools.onclick=e=>{const rb=e.target.closest('[data-ux-role]'),sb=e.target.closest('[data-ux-status]');if(rb){role=rb.dataset.uxRole;tools.querySelectorAll('[data-ux-role]').forEach(x=>x.classList.toggle('active',x===rb));apply()}if(sb){onlyInactive=!onlyInactive;sb.classList.toggle('active',onlyInactive);apply()}};
}

function enhanceAdminCatalog(kind){
  const page=`admin-${kind}`;if(S.page!==page||S.user?.role!=='admin'||S.adminPreview)return;const c=$('#content');if(!c||c.dataset[`ux${kind}`]==='1')return;c.dataset[`ux${kind}`]='1';const d=S.admin;if(!d)return;
  const isCourses=kind==='courses',items=isCourses?d.courses:d.subjects,assignments=d.assignments||[],students=(d.users||[]).filter(u=>u.active&&u.role==='student').length;
  const stats=isCourses?[['Cursos activos',items.length],['Estudiantes activos',students],['Clases asignadas',assignments.filter(a=>a.active!==false).length]]:[['Materias',items.length],['Con clases',items.filter(s=>assignments.some(a=>a.subjectId===s.id&&a.active!==false)).length],['Asignaciones',assignments.filter(a=>a.active!==false).length]];
  const grid=c.querySelector('.grid.cols-3');if(grid){grid.classList.add('ux-manage-grid');grid.insertAdjacentHTML('beforebegin',summaryHtml(stats));[...grid.children].forEach(x=>{if(!x.classList.contains('card'))return;x.dataset.uxManagedCard='1';x.dataset.uxSearch=escapeAttr(x.textContent)})}
  const tools=document.createElement('div');tools.className='ux-section-tools';tools.innerHTML=`<div class="ux-section-tools-copy"><strong>${isCourses?'Organiza tus cursos':'Encuentra una materia'}</strong><small>${isCourses?'Busca por nombre y revisa rápidamente su matrícula.':'Busca por nombre y revisa dónde se está impartiendo.'}</small></div><div class="ux-filter-row"><input class="search" id="uxCatalogSearch" placeholder="Buscar ${isCourses?'curso':'materia'}"></div>`;grid?.before(tools);
  const input=$('#uxCatalogSearch');if(input)input.oninput=()=>{const q=escapeAttr(input.value),cards=[...grid.querySelectorAll('[data-ux-managed-card]')];let n=0;cards.forEach(x=>{x.hidden=!!q&&!x.dataset.uxSearch.includes(q);if(!x.hidden)n++});noResults(grid,n===0)};
  const panel=c.querySelector('.panel');if(panel&&!panel.querySelector('.ux-assignment-meta')){const meta=document.createElement('div');meta.className='ux-assignment-meta muted';meta.style.cssText='padding:0 14px 12px;font-size:10px';meta.textContent=`${assignments.filter(a=>a.active!==false).length} asignaciones activas en el año actual`;panel.querySelector('.toolbar')?.after(meta)}
}

function enhanceAttendance(){
  if(S.page!=='student-attendance')return;const c=$('#content');if(!c||c.dataset.uxAttendance==='1')return;c.dataset.uxAttendance='1';const card=[...c.querySelectorAll('.student-att-card')].find(x=>x.querySelector('.student-att-table'));if(!card)return;const head=card.querySelector('.student-att-card-head'),rows=[...card.querySelectorAll('tbody tr')];if(!head||!rows.length)return;head.classList.add('ux-with-filter');const controls=document.createElement('div');controls.className='ux-att-controls';controls.innerHTML='<button class="ux-filter-chip active" data-att-view="all">Todos</button><button class="ux-filter-chip" data-att-view="present">Presentes</button><button class="ux-filter-chip" data-att-view="absent">Ausentes</button><span class="ux-att-count"></span>';head.appendChild(controls);let view='all';const apply=()=>{let shown=0;rows.forEach(r=>{const state=r.querySelector('.student-att-state')?.classList.contains('absent')?'absent':'present';r.hidden=view!=='all'&&state!==view;if(!r.hidden)shown++});controls.querySelector('.ux-att-count').textContent=`${shown} registro${shown===1?'':'s'}`};controls.onclick=e=>{const b=e.target.closest('[data-att-view]');if(!b)return;view=b.dataset.attView;controls.querySelectorAll('[data-att-view]').forEach(x=>x.classList.toggle('active',x===b));apply()};apply();
}

function enhanceHistory(){
  if(!String(S.page||'').includes('history'))return;const c=$('#content');if(!c||c.dataset.uxHistory==='1')return;c.dataset.uxHistory='1';const grid=c.querySelector('.history-grid');if(!grid)return;const tip=document.createElement('div');tip.className='ux-history-tip';tip.innerHTML='<span>i</span><div><strong>Historial conservado por año</strong><br>Selecciona un año para revisar su detalle. La información histórica es de consulta y no modifica los registros actuales.</div>';grid.before(tip);const buttons=[...grid.querySelectorAll('button.history-card')];if(buttons.length){const mark=b=>{buttons.forEach(x=>x.classList.toggle('ux-selected',x===b));b?.setAttribute('aria-pressed','true');buttons.filter(x=>x!==b).forEach(x=>x.setAttribute('aria-pressed','false'))};mark(buttons[0]);buttons.forEach(b=>b.addEventListener('click',()=>{mark(b);setTimeout(()=>$('#studentHistoryDetail,#teacherHistoryDetail')?.scrollIntoView({behavior:'smooth',block:'start'}),50)}))}
}

function enhanceDashboard(){
  if(!String(S.page||'').endsWith('-dashboard'))return;const c=$('#content');if(!c||c.dataset.uxDashboard==='1')return;c.dataset.uxDashboard='1';const head=c.querySelector('.dash-head');if(!head)return;const role=S.user?.role,actions=document.createElement('div');actions.className='ux-dash-actions';const defs=role==='student'?[['Asistencia','student-attendance'],['Calendario','student-calendar'],['Mi perfil','student-profile']]:role==='teacher'?[['Mis clases','teacher-home'],['Calendario','teacher-calendar'],['Planificación','teacher-planning']]:[['Usuarios','admin-users'],['Estadísticas','admin-statistics'],['Buscar','admin-search']];actions.innerHTML=defs.map(([label,page],i)=>`<button type="button" class="btn ${i===0?'secondary':'ghost'}" data-ux-dash-go="${page}">${U.esc(label)}</button>`).join('');head.after(actions);actions.onclick=e=>{const b=e.target.closest('[data-ux-dash-go]');if(b)U.navigate(b.dataset.uxDashGo)};
}

function run(){enhanceAdminUsers();enhanceAdminCatalog('courses');enhanceAdminCatalog('subjects');enhanceAttendance();enhanceHistory();enhanceDashboard()}
const wrap=fnName=>{const base=U[fnName];if(typeof base!=='function')return;U[fnName]=async(...args)=>{const out=await base(...args);setTimeout(run,0);return out}};
['renderAdminUsers','renderAdminCourses','renderAdminSubjects','renderStudentAttendance','renderDashboard'].forEach(wrap);
const content=$('#content');if(content){let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;run()})}).observe(content,{childList:true,subtree:false})}
setTimeout(run,0);
})();